INSERT INTO tipo_acao_disciplinar(id_tipo_acao_disciplinar, acao_disciplinar)
VALUES(1, 'Cartão Amarelo'),
	(2, 'Cartão Vermelho'),
	(3,'Time-out'),
	(4,'Expulsão'),
	(5,'Cartão Azul'),
	(6,'Falta');
	
/* 1 ao 25 c.amarelo futebol, 26 ao 30 c.vermelho futebol, 31 a 40 amarelo futsal, 40 a 45 vermelho futsal,46 a 70 faltas basquete,71 a 75 expulsao basquete, 76 a 80 c.amarelo volei, 81 a 90 c.amarelo andebol, 91 a 100c.azul hoqeui */
insert into acoes_disciplinares (id_acao_disciplinar, id_tipo_acao_disciplinar, tempo_jogo) values (1, 1, 42);
insert into acoes_disciplinares (id_acao_disciplinar, id_tipo_acao_disciplinar, tempo_jogo) values (2, 1, 64);
insert into acoes_disciplinares (id_acao_disciplinar, id_tipo_acao_disciplinar,tempo_jogo) values (3, 1, 71);
insert into acoes_disciplinares (id_acao_disciplinar, id_tipo_acao_disciplinar,tempo_jogo) values (4, 1, 71);
insert into acoes_disciplinares (id_acao_disciplinar, id_tipo_acao_disciplinar,tempo_jogo) values (5, 1, 90);
insert into acoes_disciplinares (id_acao_disciplinar, id_tipo_acao_disciplinar,tempo_jogo) values (6, 1, 53);
insert into acoes_disciplinares (id_acao_disciplinar, id_tipo_acao_disciplinar,tempo_jogo) values (7, 1, 43);
insert into acoes_disciplinares (id_acao_disciplinar, id_tipo_acao_disciplinar,tempo_jogo) values (8, 1, 71);
insert into acoes_disciplinares (id_acao_disciplinar, id_tipo_acao_disciplinar,tempo_jogo) values (9, 1, 70);
insert into acoes_disciplinares (id_acao_disciplinar, id_tipo_acao_disciplinar,tempo_jogo) values (10, 1, 88);
insert into acoes_disciplinares (id_acao_disciplinar, id_tipo_acao_disciplinar,tempo_jogo) values (11, 1, 20);
insert into acoes_disciplinares (id_acao_disciplinar, id_tipo_acao_disciplinar,tempo_jogo) values (12, 1, 47);
insert into acoes_disciplinares (id_acao_disciplinar, id_tipo_acao_disciplinar,tempo_jogo) values (13, 1, 81);
insert into acoes_disciplinares (id_acao_disciplinar, id_tipo_acao_disciplinar,tempo_jogo) values (14, 1, 35);
insert into acoes_disciplinares (id_acao_disciplinar, id_tipo_acao_disciplinar,tempo_jogo) values (15, 1, 48);
insert into acoes_disciplinares (id_acao_disciplinar, id_tipo_acao_disciplinar,tempo_jogo) values (16, 1, 19);
insert into acoes_disciplinares (id_acao_disciplinar, id_tipo_acao_disciplinar,tempo_jogo) values (17, 1, 7);
insert into acoes_disciplinares (id_acao_disciplinar, id_tipo_acao_disciplinar,tempo_jogo) values (18, 1, 34);
insert into acoes_disciplinares (id_acao_disciplinar, id_tipo_acao_disciplinar,tempo_jogo) values (19, 1, 49);
insert into acoes_disciplinares (id_acao_disciplinar, id_tipo_acao_disciplinar,tempo_jogo) values (20, 1, 46);
insert into acoes_disciplinares (id_acao_disciplinar, id_tipo_acao_disciplinar,tempo_jogo) values (21, 1, 63);
insert into acoes_disciplinares (id_acao_disciplinar, id_tipo_acao_disciplinar,tempo_jogo) values (22, 1, 19);
insert into acoes_disciplinares (id_acao_disciplinar, id_tipo_acao_disciplinar,tempo_jogo) values (23, 1, 62);
insert into acoes_disciplinares (id_acao_disciplinar, id_tipo_acao_disciplinar,tempo_jogo) values (24, 1, 22);
insert into acoes_disciplinares (id_acao_disciplinar, id_tipo_acao_disciplinar,tempo_jogo) values (25, 1, 52);
insert into acoes_disciplinares (id_acao_disciplinar, id_tipo_acao_disciplinar,tempo_jogo) values (26, 2, 50);
insert into acoes_disciplinares (id_acao_disciplinar, id_tipo_acao_disciplinar,tempo_jogo) values (27, 2, 50);
insert into acoes_disciplinares (id_acao_disciplinar, id_tipo_acao_disciplinar,tempo_jogo) values (28, 2, 80);
insert into acoes_disciplinares (id_acao_disciplinar, id_tipo_acao_disciplinar,tempo_jogo) values (29, 2, 13);
insert into acoes_disciplinares (id_acao_disciplinar, id_tipo_acao_disciplinar,tempo_jogo) values (30, 2, 78);
insert into acoes_disciplinares (id_acao_disciplinar, id_tipo_acao_disciplinar,tempo_jogo) values (31, 1, 35);
insert into acoes_disciplinares (id_acao_disciplinar, id_tipo_acao_disciplinar,tempo_jogo) values (32, 1, 36);
insert into acoes_disciplinares (id_acao_disciplinar, id_tipo_acao_disciplinar,tempo_jogo) values (33, 1, 22);
insert into acoes_disciplinares (id_acao_disciplinar, id_tipo_acao_disciplinar,tempo_jogo) values (34, 1, 21);
insert into acoes_disciplinares (id_acao_disciplinar, id_tipo_acao_disciplinar,tempo_jogo) values (35, 1, 3);
insert into acoes_disciplinares (id_acao_disciplinar, id_tipo_acao_disciplinar,tempo_jogo) values (36, 1, 36);
insert into acoes_disciplinares (id_acao_disciplinar, id_tipo_acao_disciplinar,tempo_jogo) values (37, 1, 19);
insert into acoes_disciplinares (id_acao_disciplinar, id_tipo_acao_disciplinar,tempo_jogo) values (38, 1, 20);
insert into acoes_disciplinares (id_acao_disciplinar, id_tipo_acao_disciplinar,tempo_jogo) values (39, 1, 39);
insert into acoes_disciplinares (id_acao_disciplinar, id_tipo_acao_disciplinar,tempo_jogo) values (40, 1, 16);
insert into acoes_disciplinares (id_acao_disciplinar, id_tipo_acao_disciplinar,tempo_jogo) values (41, 2, 5);
insert into acoes_disciplinares (id_acao_disciplinar, id_tipo_acao_disciplinar,tempo_jogo) values (42, 2, 32);
insert into acoes_disciplinares (id_acao_disciplinar, id_tipo_acao_disciplinar,tempo_jogo) values (43, 2, 30);
insert into acoes_disciplinares (id_acao_disciplinar, id_tipo_acao_disciplinar,tempo_jogo) values (44, 2, 4);
insert into acoes_disciplinares (id_acao_disciplinar, id_tipo_acao_disciplinar,tempo_jogo) values (45, 2, 17);
insert into acoes_disciplinares (id_acao_disciplinar, id_tipo_acao_disciplinar,tempo_jogo) values (46, 6, 18);
insert into acoes_disciplinares (id_acao_disciplinar, id_tipo_acao_disciplinar,tempo_jogo) values (47, 6, 14);
insert into acoes_disciplinares (id_acao_disciplinar, id_tipo_acao_disciplinar,tempo_jogo) values (48, 6, 10);
insert into acoes_disciplinares (id_acao_disciplinar, id_tipo_acao_disciplinar,tempo_jogo) values (49, 6, 32);
insert into acoes_disciplinares (id_acao_disciplinar, id_tipo_acao_disciplinar,tempo_jogo) values (50, 6, 12);
insert into acoes_disciplinares (id_acao_disciplinar, id_tipo_acao_disciplinar,tempo_jogo) values (51, 6, 24);
insert into acoes_disciplinares (id_acao_disciplinar, id_tipo_acao_disciplinar,tempo_jogo) values (52, 6, 40);
insert into acoes_disciplinares (id_acao_disciplinar, id_tipo_acao_disciplinar,tempo_jogo) values (53, 6, 31);
insert into acoes_disciplinares (id_acao_disciplinar, id_tipo_acao_disciplinar,tempo_jogo) values (54, 6, 20);
insert into acoes_disciplinares (id_acao_disciplinar, id_tipo_acao_disciplinar,tempo_jogo) values (55, 6, 14);
insert into acoes_disciplinares (id_acao_disciplinar, id_tipo_acao_disciplinar,tempo_jogo) values (56, 6, 9);
insert into acoes_disciplinares (id_acao_disciplinar, id_tipo_acao_disciplinar,tempo_jogo) values (57, 6, 21);
insert into acoes_disciplinares (id_acao_disciplinar, id_tipo_acao_disciplinar,tempo_jogo) values (58, 6, 31);
insert into acoes_disciplinares (id_acao_disciplinar, id_tipo_acao_disciplinar,tempo_jogo) values (59, 6, 19);
insert into acoes_disciplinares (id_acao_disciplinar, id_tipo_acao_disciplinar,tempo_jogo) values (60, 6, 4);
insert into acoes_disciplinares (id_acao_disciplinar, id_tipo_acao_disciplinar,tempo_jogo) values (61, 6, 6);
insert into acoes_disciplinares (id_acao_disciplinar, id_tipo_acao_disciplinar,tempo_jogo) values (62, 6, 39);
insert into acoes_disciplinares (id_acao_disciplinar, id_tipo_acao_disciplinar,tempo_jogo) values (63, 6, 22);
insert into acoes_disciplinares (id_acao_disciplinar, id_tipo_acao_disciplinar,tempo_jogo) values (64, 6, 7);
insert into acoes_disciplinares (id_acao_disciplinar, id_tipo_acao_disciplinar,tempo_jogo) values (65, 6, 34);
insert into acoes_disciplinares (id_acao_disciplinar, id_tipo_acao_disciplinar,tempo_jogo) values (66, 6, 36);
insert into acoes_disciplinares (id_acao_disciplinar, id_tipo_acao_disciplinar,tempo_jogo) values (67, 6, 15);
insert into acoes_disciplinares (id_acao_disciplinar, id_tipo_acao_disciplinar,tempo_jogo) values (68, 6, 16);
insert into acoes_disciplinares (id_acao_disciplinar, id_tipo_acao_disciplinar,tempo_jogo) values (69, 6, 17);
insert into acoes_disciplinares (id_acao_disciplinar, id_tipo_acao_disciplinar,tempo_jogo) values (70, 6, 35);
insert into acoes_disciplinares (id_acao_disciplinar, id_tipo_acao_disciplinar,tempo_jogo) values (71, 4, 28);
insert into acoes_disciplinares (id_acao_disciplinar, id_tipo_acao_disciplinar,tempo_jogo) values (72, 4, 13);
insert into acoes_disciplinares (id_acao_disciplinar, id_tipo_acao_disciplinar,tempo_jogo) values (73, 4, 24);
insert into acoes_disciplinares (id_acao_disciplinar, id_tipo_acao_disciplinar,tempo_jogo) values (74, 4, 6);
insert into acoes_disciplinares (id_acao_disciplinar, id_tipo_acao_disciplinar,tempo_jogo) values (75, 4, 34);
insert into acoes_disciplinares (id_acao_disciplinar, id_tipo_acao_disciplinar,tempo_jogo) values (76, 1, 26);
insert into acoes_disciplinares (id_acao_disciplinar, id_tipo_acao_disciplinar,tempo_jogo) values (77, 1, 40);
insert into acoes_disciplinares (id_acao_disciplinar, id_tipo_acao_disciplinar,tempo_jogo) values (78, 1, 36);
insert into acoes_disciplinares (id_acao_disciplinar, id_tipo_acao_disciplinar,tempo_jogo) values (79, 1, 26);
insert into acoes_disciplinares (id_acao_disciplinar, id_tipo_acao_disciplinar,tempo_jogo) values (80, 1, 14);
insert into acoes_disciplinares (id_acao_disciplinar, id_tipo_acao_disciplinar,tempo_jogo) values (81, 1, 5);
insert into acoes_disciplinares (id_acao_disciplinar, id_tipo_acao_disciplinar,tempo_jogo) values (82, 1, 15);
insert into acoes_disciplinares (id_acao_disciplinar, id_tipo_acao_disciplinar,tempo_jogo) values (83, 1, 29);
insert into acoes_disciplinares (id_acao_disciplinar, id_tipo_acao_disciplinar,tempo_jogo) values (84, 1, 19);
insert into acoes_disciplinares (id_acao_disciplinar, id_tipo_acao_disciplinar,tempo_jogo) values (85, 1, 26);
insert into acoes_disciplinares (id_acao_disciplinar, id_tipo_acao_disciplinar,tempo_jogo) values (86, 1, 32);
insert into acoes_disciplinares (id_acao_disciplinar, id_tipo_acao_disciplinar,tempo_jogo) values (87, 1, 35);
insert into acoes_disciplinares (id_acao_disciplinar, id_tipo_acao_disciplinar,tempo_jogo) values (88, 1, 38);
insert into acoes_disciplinares (id_acao_disciplinar, id_tipo_acao_disciplinar,tempo_jogo) values (89, 1,30);
insert into acoes_disciplinares (id_acao_disciplinar, id_tipo_acao_disciplinar,tempo_jogo) values (90, 1, 10);
insert into acoes_disciplinares (id_acao_disciplinar, id_tipo_acao_disciplinar,tempo_jogo) values (91, 5, 20);
insert into acoes_disciplinares (id_acao_disciplinar, id_tipo_acao_disciplinar,tempo_jogo) values (92, 5, 16);
insert into acoes_disciplinares (id_acao_disciplinar, id_tipo_acao_disciplinar,tempo_jogo) values (93, 5, 36);
insert into acoes_disciplinares (id_acao_disciplinar, id_tipo_acao_disciplinar,tempo_jogo) values (94, 5,26);
insert into acoes_disciplinares (id_acao_disciplinar, id_tipo_acao_disciplinar,tempo_jogo) values (95, 5,39);
insert into acoes_disciplinares (id_acao_disciplinar, id_tipo_acao_disciplinar,tempo_jogo) values (96, 5,17);
insert into acoes_disciplinares (id_acao_disciplinar, id_tipo_acao_disciplinar,tempo_jogo) values (97, 5, 6);
insert into acoes_disciplinares (id_acao_disciplinar, id_tipo_acao_disciplinar,tempo_jogo) values (98, 5, 17);
insert into acoes_disciplinares (id_acao_disciplinar, id_tipo_acao_disciplinar,tempo_jogo) values (99, 5, 4);
insert into acoes_disciplinares (id_acao_disciplinar, id_tipo_acao_disciplinar,tempo_jogo) values (100, 5, 11);



INSERT INTO tipo_pontuacao(id_tipo_pontuacao, tipo_pontuacao)
VALUES(1, 'Golo'),
	(2, 'Ponto'),
	(3, 'Set');
	
/* 1 ao 100 futebol, 101 ao 200 futsal, 201 ao 400 basket, 401 ao 500 volei, 501 ao 600 andebol, 601 ao 700 hoquei*/
insert into pontuacoes (id_pontuacao, id_tipo_pontuacao, pontuacao, tempo_jogo) values (1, 1, 1, 12);
insert into pontuacoes (id_pontuacao, id_tipo_pontuacao, pontuacao, tempo_jogo) values (2, 1, 1, 27);
insert into pontuacoes (id_pontuacao, id_tipo_pontuacao, pontuacao, tempo_jogo) values (3, 1, 1, 44);
insert into pontuacoes (id_pontuacao, id_tipo_pontuacao, pontuacao, tempo_jogo) values (4, 1, 1, 38);
insert into pontuacoes (id_pontuacao, id_tipo_pontuacao, pontuacao, tempo_jogo) values (5, 1, 1, 70);
insert into pontuacoes (id_pontuacao, id_tipo_pontuacao, pontuacao, tempo_jogo) values (6, 1, 1, 79);
insert into pontuacoes (id_pontuacao, id_tipo_pontuacao, pontuacao, tempo_jogo) values (7, 1, 1, 57);
insert into pontuacoes (id_pontuacao, id_tipo_pontuacao, pontuacao, tempo_jogo) values (8, 1, 1, 8);
insert into pontuacoes (id_pontuacao, id_tipo_pontuacao, pontuacao, tempo_jogo) values (9, 1, 1, 71);
insert into pontuacoes (id_pontuacao, id_tipo_pontuacao, pontuacao, tempo_jogo) values (10, 1, 1, 78);
insert into pontuacoes (id_pontuacao, id_tipo_pontuacao, pontuacao, tempo_jogo) values (11, 1, 1, 32);
insert into pontuacoes (id_pontuacao, id_tipo_pontuacao, pontuacao, tempo_jogo) values (12, 1, 1, 16);
insert into pontuacoes (id_pontuacao, id_tipo_pontuacao, pontuacao, tempo_jogo) values (13, 1, 1, 20);
insert into pontuacoes (id_pontuacao, id_tipo_pontuacao, pontuacao, tempo_jogo) values (14, 1, 1, 21);
insert into pontuacoes (id_pontuacao, id_tipo_pontuacao, pontuacao, tempo_jogo) values (15, 1, 1, 76);
insert into pontuacoes (id_pontuacao, id_tipo_pontuacao, pontuacao, tempo_jogo) values (16, 1, 1, 19);
insert into pontuacoes (id_pontuacao, id_tipo_pontuacao, pontuacao, tempo_jogo) values (17, 1, 1, 73);
insert into pontuacoes (id_pontuacao, id_tipo_pontuacao, pontuacao, tempo_jogo) values (18, 1, 1, 51);
insert into pontuacoes (id_pontuacao, id_tipo_pontuacao, pontuacao, tempo_jogo) values (19, 1, 1, 42);
insert into pontuacoes (id_pontuacao, id_tipo_pontuacao, pontuacao, tempo_jogo) values (20, 1, 1, 64);
insert into pontuacoes (id_pontuacao, id_tipo_pontuacao, pontuacao, tempo_jogo) values (21, 1, 1, 45);
insert into pontuacoes (id_pontuacao, id_tipo_pontuacao, pontuacao, tempo_jogo) values (22, 1, 1, 34);
insert into pontuacoes (id_pontuacao, id_tipo_pontuacao, pontuacao, tempo_jogo) values (23, 1, 1, 27);
insert into pontuacoes (id_pontuacao, id_tipo_pontuacao, pontuacao, tempo_jogo) values (24, 1, 1, 34);
insert into pontuacoes (id_pontuacao, id_tipo_pontuacao, pontuacao, tempo_jogo) values (25, 1, 1, 47);
insert into pontuacoes (id_pontuacao, id_tipo_pontuacao, pontuacao, tempo_jogo) values (26, 1, 1, 1);
insert into pontuacoes (id_pontuacao, id_tipo_pontuacao, pontuacao, tempo_jogo) values (27, 1, 1, 54);
insert into pontuacoes (id_pontuacao, id_tipo_pontuacao, pontuacao, tempo_jogo) values (28, 1, 1, 47);
insert into pontuacoes (id_pontuacao, id_tipo_pontuacao, pontuacao, tempo_jogo) values (29, 1, 1, 72);
insert into pontuacoes (id_pontuacao, id_tipo_pontuacao, pontuacao, tempo_jogo) values (30, 1, 1, 75);
insert into pontuacoes (id_pontuacao, id_tipo_pontuacao, pontuacao, tempo_jogo) values (31, 1, 1, 33);
insert into pontuacoes (id_pontuacao, id_tipo_pontuacao, pontuacao, tempo_jogo) values (32, 1, 1, 82);
insert into pontuacoes (id_pontuacao, id_tipo_pontuacao, pontuacao, tempo_jogo) values (33, 1, 1, 18);
insert into pontuacoes (id_pontuacao, id_tipo_pontuacao, pontuacao, tempo_jogo) values (34, 1, 1, 33);
insert into pontuacoes (id_pontuacao, id_tipo_pontuacao, pontuacao, tempo_jogo) values (35, 1, 1, 33);
insert into pontuacoes (id_pontuacao, id_tipo_pontuacao, pontuacao, tempo_jogo) values (36, 1, 1, 2);
insert into pontuacoes (id_pontuacao, id_tipo_pontuacao, pontuacao, tempo_jogo) values (37, 1, 1, 27);
insert into pontuacoes (id_pontuacao, id_tipo_pontuacao, pontuacao, tempo_jogo) values (38, 1, 1, 31);
insert into pontuacoes (id_pontuacao, id_tipo_pontuacao, pontuacao, tempo_jogo) values (39, 1, 1, 73);
insert into pontuacoes (id_pontuacao, id_tipo_pontuacao, pontuacao, tempo_jogo) values (40, 1, 1, 10);
insert into pontuacoes (id_pontuacao, id_tipo_pontuacao, pontuacao, tempo_jogo) values (41, 1, 1, 46);
insert into pontuacoes (id_pontuacao, id_tipo_pontuacao, pontuacao, tempo_jogo) values (42, 1, 1, 76);
insert into pontuacoes (id_pontuacao, id_tipo_pontuacao, pontuacao, tempo_jogo) values (43, 1, 1, 14);
insert into pontuacoes (id_pontuacao, id_tipo_pontuacao, pontuacao, tempo_jogo) values (44, 1, 1, 25);
insert into pontuacoes (id_pontuacao, id_tipo_pontuacao, pontuacao, tempo_jogo) values (45, 1, 1, 37);
insert into pontuacoes (id_pontuacao, id_tipo_pontuacao, pontuacao, tempo_jogo) values (46, 1, 1, 63);
insert into pontuacoes (id_pontuacao, id_tipo_pontuacao, pontuacao, tempo_jogo) values (47, 1, 1, 85);
insert into pontuacoes (id_pontuacao, id_tipo_pontuacao, pontuacao, tempo_jogo) values (48, 1, 1, 53);
insert into pontuacoes (id_pontuacao, id_tipo_pontuacao, pontuacao, tempo_jogo) values (49, 1, 1, 63);
insert into pontuacoes (id_pontuacao, id_tipo_pontuacao, pontuacao, tempo_jogo) values (50, 1, 1, 82);
insert into pontuacoes (id_pontuacao, id_tipo_pontuacao, pontuacao, tempo_jogo) values (51, 1, 1, 21);
insert into pontuacoes (id_pontuacao, id_tipo_pontuacao, pontuacao, tempo_jogo) values (52, 1, 1, 20);
insert into pontuacoes (id_pontuacao, id_tipo_pontuacao, pontuacao, tempo_jogo) values (53, 1, 1, 1);
insert into pontuacoes (id_pontuacao, id_tipo_pontuacao, pontuacao, tempo_jogo) values (54, 1, 1, 59);
insert into pontuacoes (id_pontuacao, id_tipo_pontuacao, pontuacao, tempo_jogo) values (55, 1, 1, 80);
insert into pontuacoes (id_pontuacao, id_tipo_pontuacao, pontuacao, tempo_jogo) values (56, 1, 1, 16);
insert into pontuacoes (id_pontuacao, id_tipo_pontuacao, pontuacao, tempo_jogo) values (57, 1, 1, 24);
insert into pontuacoes (id_pontuacao, id_tipo_pontuacao, pontuacao, tempo_jogo) values (58, 1, 1, 7);
insert into pontuacoes (id_pontuacao, id_tipo_pontuacao, pontuacao, tempo_jogo) values (59, 1, 1, 36);
insert into pontuacoes (id_pontuacao, id_tipo_pontuacao, pontuacao, tempo_jogo) values (60, 1, 1, 9);
insert into pontuacoes (id_pontuacao, id_tipo_pontuacao, pontuacao, tempo_jogo) values (61, 1, 1, 68);
insert into pontuacoes (id_pontuacao, id_tipo_pontuacao, pontuacao, tempo_jogo) values (62, 1, 1, 30);
insert into pontuacoes (id_pontuacao, id_tipo_pontuacao, pontuacao, tempo_jogo) values (63, 1, 1, 31);
insert into pontuacoes (id_pontuacao, id_tipo_pontuacao, pontuacao, tempo_jogo) values (64, 1, 1, 18);
insert into pontuacoes (id_pontuacao, id_tipo_pontuacao, pontuacao, tempo_jogo) values (65, 1, 1, 46);
insert into pontuacoes (id_pontuacao, id_tipo_pontuacao, pontuacao, tempo_jogo) values (66, 1, 1, 69);
insert into pontuacoes (id_pontuacao, id_tipo_pontuacao, pontuacao, tempo_jogo) values (67, 1, 1, 6);
insert into pontuacoes (id_pontuacao, id_tipo_pontuacao, pontuacao, tempo_jogo) values (68, 1, 1, 26);
insert into pontuacoes (id_pontuacao, id_tipo_pontuacao, pontuacao, tempo_jogo) values (69, 1, 1, 35);
insert into pontuacoes (id_pontuacao, id_tipo_pontuacao, pontuacao, tempo_jogo) values (70, 1, 1, 7);
insert into pontuacoes (id_pontuacao, id_tipo_pontuacao, pontuacao, tempo_jogo) values (71, 1, 1, 56);
insert into pontuacoes (id_pontuacao, id_tipo_pontuacao, pontuacao, tempo_jogo) values (72, 1, 1, 62);
insert into pontuacoes (id_pontuacao, id_tipo_pontuacao, pontuacao, tempo_jogo) values (73, 1, 1, 6);
insert into pontuacoes (id_pontuacao, id_tipo_pontuacao, pontuacao, tempo_jogo) values (74, 1, 1, 45);
insert into pontuacoes (id_pontuacao, id_tipo_pontuacao, pontuacao, tempo_jogo) values (75, 1, 1, 77);
insert into pontuacoes (id_pontuacao, id_tipo_pontuacao, pontuacao, tempo_jogo) values (76, 1, 1, 10);
insert into pontuacoes (id_pontuacao, id_tipo_pontuacao, pontuacao, tempo_jogo) values (77, 1, 1, 2);
insert into pontuacoes (id_pontuacao, id_tipo_pontuacao, pontuacao, tempo_jogo) values (78, 1, 1, 52);
insert into pontuacoes (id_pontuacao, id_tipo_pontuacao, pontuacao, tempo_jogo) values (79, 1, 1, 52);
insert into pontuacoes (id_pontuacao, id_tipo_pontuacao, pontuacao, tempo_jogo) values (80, 1, 1, 63);
insert into pontuacoes (id_pontuacao, id_tipo_pontuacao, pontuacao, tempo_jogo) values (81, 1, 1, 45);
insert into pontuacoes (id_pontuacao, id_tipo_pontuacao, pontuacao, tempo_jogo) values (82, 1, 1, 19);
insert into pontuacoes (id_pontuacao, id_tipo_pontuacao, pontuacao, tempo_jogo) values (83, 1, 1, 19);
insert into pontuacoes (id_pontuacao, id_tipo_pontuacao, pontuacao, tempo_jogo) values (84, 1, 1, 6);
insert into pontuacoes (id_pontuacao, id_tipo_pontuacao, pontuacao, tempo_jogo) values (85, 1, 1, 6);
insert into pontuacoes (id_pontuacao, id_tipo_pontuacao, pontuacao, tempo_jogo) values (86, 1, 1, 14);
insert into pontuacoes (id_pontuacao, id_tipo_pontuacao, pontuacao, tempo_jogo) values (87, 1, 1, 26);
insert into pontuacoes (id_pontuacao, id_tipo_pontuacao, pontuacao, tempo_jogo) values (88, 1, 1, 2);
insert into pontuacoes (id_pontuacao, id_tipo_pontuacao, pontuacao, tempo_jogo) values (89, 1, 1, 21);
insert into pontuacoes (id_pontuacao, id_tipo_pontuacao, pontuacao, tempo_jogo) values (90, 1, 1, 51);
insert into pontuacoes (id_pontuacao, id_tipo_pontuacao, pontuacao, tempo_jogo) values (91, 1, 1, 34);
insert into pontuacoes (id_pontuacao, id_tipo_pontuacao, pontuacao, tempo_jogo) values (92, 1, 1, 80);
insert into pontuacoes (id_pontuacao, id_tipo_pontuacao, pontuacao, tempo_jogo) values (93, 1, 1, 51);
insert into pontuacoes (id_pontuacao, id_tipo_pontuacao, pontuacao, tempo_jogo) values (94, 1, 1, 36);
insert into pontuacoes (id_pontuacao, id_tipo_pontuacao, pontuacao, tempo_jogo) values (95, 1, 1, 17);
insert into pontuacoes (id_pontuacao, id_tipo_pontuacao, pontuacao, tempo_jogo) values (96, 1, 1, 28);
insert into pontuacoes (id_pontuacao, id_tipo_pontuacao, pontuacao, tempo_jogo) values (97, 1, 1, 74);
insert into pontuacoes (id_pontuacao, id_tipo_pontuacao, pontuacao, tempo_jogo) values (98, 1, 1, 86);
insert into pontuacoes (id_pontuacao, id_tipo_pontuacao, pontuacao, tempo_jogo) values (99, 1, 1, 51);
insert into pontuacoes (id_pontuacao, id_tipo_pontuacao, pontuacao, tempo_jogo) values (100, 1, 1, 7);
insert into pontuacoes (id_pontuacao, id_tipo_pontuacao, pontuacao, tempo_jogo) values (101, 1, 1, 34);
insert into pontuacoes (id_pontuacao, id_tipo_pontuacao, pontuacao, tempo_jogo) values (102, 1, 1, 4);
insert into pontuacoes (id_pontuacao, id_tipo_pontuacao, pontuacao, tempo_jogo) values (103, 1, 1, 17);
insert into pontuacoes (id_pontuacao, id_tipo_pontuacao, pontuacao, tempo_jogo) values (104, 1, 1, 11);
insert into pontuacoes (id_pontuacao, id_tipo_pontuacao, pontuacao, tempo_jogo) values (105, 1, 1, 24);
insert into pontuacoes (id_pontuacao, id_tipo_pontuacao, pontuacao, tempo_jogo) values (106, 1, 1, 15);
insert into pontuacoes (id_pontuacao, id_tipo_pontuacao, pontuacao, tempo_jogo) values (107, 1, 1, 21);
insert into pontuacoes (id_pontuacao, id_tipo_pontuacao, pontuacao, tempo_jogo) values (108, 1, 1, 28);
insert into pontuacoes (id_pontuacao, id_tipo_pontuacao, pontuacao, tempo_jogo) values (109, 1, 1, 27);
insert into pontuacoes (id_pontuacao, id_tipo_pontuacao, pontuacao, tempo_jogo) values (110, 1, 1, 40);
insert into pontuacoes (id_pontuacao, id_tipo_pontuacao, pontuacao, tempo_jogo) values (111, 1, 1, 20);
insert into pontuacoes (id_pontuacao, id_tipo_pontuacao, pontuacao, tempo_jogo) values (112, 1, 1, 19);
insert into pontuacoes (id_pontuacao, id_tipo_pontuacao, pontuacao, tempo_jogo) values (113, 1, 1, 6);
insert into pontuacoes (id_pontuacao, id_tipo_pontuacao, pontuacao, tempo_jogo) values (114, 1, 1, 3);
insert into pontuacoes (id_pontuacao, id_tipo_pontuacao, pontuacao, tempo_jogo) values (115, 1, 1, 14);
insert into pontuacoes (id_pontuacao, id_tipo_pontuacao, pontuacao, tempo_jogo) values (116, 1, 1, 9);
insert into pontuacoes (id_pontuacao, id_tipo_pontuacao, pontuacao, tempo_jogo) values (117, 1, 1, 28);
insert into pontuacoes (id_pontuacao, id_tipo_pontuacao, pontuacao, tempo_jogo) values (118, 1, 1, 1);
insert into pontuacoes (id_pontuacao, id_tipo_pontuacao, pontuacao, tempo_jogo) values (119, 1, 1, 25);
insert into pontuacoes (id_pontuacao, id_tipo_pontuacao, pontuacao, tempo_jogo) values (120, 1, 1, 16);
insert into pontuacoes (id_pontuacao, id_tipo_pontuacao, pontuacao, tempo_jogo) values (121, 1, 1, 26);
insert into pontuacoes (id_pontuacao, id_tipo_pontuacao, pontuacao, tempo_jogo) values (122, 1, 1, 10);
insert into pontuacoes (id_pontuacao, id_tipo_pontuacao, pontuacao, tempo_jogo) values (123, 1, 1, 14);
insert into pontuacoes (id_pontuacao, id_tipo_pontuacao, pontuacao, tempo_jogo) values (124, 1, 1, 5);
insert into pontuacoes (id_pontuacao, id_tipo_pontuacao, pontuacao, tempo_jogo) values (125, 1, 1, 35);
insert into pontuacoes (id_pontuacao, id_tipo_pontuacao, pontuacao, tempo_jogo) values (126, 1, 1, 6);
insert into pontuacoes (id_pontuacao, id_tipo_pontuacao, pontuacao, tempo_jogo) values (127, 1, 1, 5);
insert into pontuacoes (id_pontuacao, id_tipo_pontuacao, pontuacao, tempo_jogo) values (128, 1, 1, 25);
insert into pontuacoes (id_pontuacao, id_tipo_pontuacao, pontuacao, tempo_jogo) values (129, 1, 1, 24);
insert into pontuacoes (id_pontuacao, id_tipo_pontuacao, pontuacao, tempo_jogo) values (130, 1, 1, 37);
insert into pontuacoes (id_pontuacao, id_tipo_pontuacao, pontuacao, tempo_jogo) values (131, 1, 1, 3);
insert into pontuacoes (id_pontuacao, id_tipo_pontuacao, pontuacao, tempo_jogo) values (132, 1, 1, 22);
insert into pontuacoes (id_pontuacao, id_tipo_pontuacao, pontuacao, tempo_jogo) values (133, 1, 1, 38);
insert into pontuacoes (id_pontuacao, id_tipo_pontuacao, pontuacao, tempo_jogo) values (134, 1, 1, 18);
insert into pontuacoes (id_pontuacao, id_tipo_pontuacao, pontuacao, tempo_jogo) values (135, 1, 1, 19);
insert into pontuacoes (id_pontuacao, id_tipo_pontuacao, pontuacao, tempo_jogo) values (136, 1, 1, 20);
insert into pontuacoes (id_pontuacao, id_tipo_pontuacao, pontuacao, tempo_jogo) values (137, 1, 1, 3);
insert into pontuacoes (id_pontuacao, id_tipo_pontuacao, pontuacao, tempo_jogo) values (138, 1, 1, 14);
insert into pontuacoes (id_pontuacao, id_tipo_pontuacao, pontuacao, tempo_jogo) values (139, 1, 1, 26);
insert into pontuacoes (id_pontuacao, id_tipo_pontuacao, pontuacao, tempo_jogo) values (140, 1, 1, 39);
insert into pontuacoes (id_pontuacao, id_tipo_pontuacao, pontuacao, tempo_jogo) values (141, 1, 1, 4);
insert into pontuacoes (id_pontuacao, id_tipo_pontuacao, pontuacao, tempo_jogo) values (142, 1, 1, 27);
insert into pontuacoes (id_pontuacao, id_tipo_pontuacao, pontuacao, tempo_jogo) values (143, 1, 1, 15);
insert into pontuacoes (id_pontuacao, id_tipo_pontuacao, pontuacao, tempo_jogo) values (144, 1, 1, 25);
insert into pontuacoes (id_pontuacao, id_tipo_pontuacao, pontuacao, tempo_jogo) values (145, 1, 1, 3);
insert into pontuacoes (id_pontuacao, id_tipo_pontuacao, pontuacao, tempo_jogo) values (146, 1, 1, 39);
insert into pontuacoes (id_pontuacao, id_tipo_pontuacao, pontuacao, tempo_jogo) values (147, 1, 1, 25);
insert into pontuacoes (id_pontuacao, id_tipo_pontuacao, pontuacao, tempo_jogo) values (148, 1, 1, 13);
insert into pontuacoes (id_pontuacao, id_tipo_pontuacao, pontuacao, tempo_jogo) values (149, 1, 1, 27);
insert into pontuacoes (id_pontuacao, id_tipo_pontuacao, pontuacao, tempo_jogo) values (150, 1, 1, 12);
insert into pontuacoes (id_pontuacao, id_tipo_pontuacao, pontuacao, tempo_jogo) values (151, 1, 1, 12);
insert into pontuacoes (id_pontuacao, id_tipo_pontuacao, pontuacao, tempo_jogo) values (152, 1, 1, 37);
insert into pontuacoes (id_pontuacao, id_tipo_pontuacao, pontuacao, tempo_jogo) values (153, 1, 1, 28);
insert into pontuacoes (id_pontuacao, id_tipo_pontuacao, pontuacao, tempo_jogo) values (154, 1, 1, 31);
insert into pontuacoes (id_pontuacao, id_tipo_pontuacao, pontuacao, tempo_jogo) values (155, 1, 1, 25);
insert into pontuacoes (id_pontuacao, id_tipo_pontuacao, pontuacao, tempo_jogo) values (156, 1, 1, 18);
insert into pontuacoes (id_pontuacao, id_tipo_pontuacao, pontuacao, tempo_jogo) values (157, 1, 1, 15);
insert into pontuacoes (id_pontuacao, id_tipo_pontuacao, pontuacao, tempo_jogo) values (158, 1, 1, 35);
insert into pontuacoes (id_pontuacao, id_tipo_pontuacao, pontuacao, tempo_jogo) values (159, 1, 1, 3);
insert into pontuacoes (id_pontuacao, id_tipo_pontuacao, pontuacao, tempo_jogo) values (160, 1, 1, 20);
insert into pontuacoes (id_pontuacao, id_tipo_pontuacao, pontuacao, tempo_jogo) values (161, 1, 1, 2);
insert into pontuacoes (id_pontuacao, id_tipo_pontuacao, pontuacao, tempo_jogo) values (162, 1, 1, 28);
insert into pontuacoes (id_pontuacao, id_tipo_pontuacao, pontuacao, tempo_jogo) values (163, 1, 1, 9);
insert into pontuacoes (id_pontuacao, id_tipo_pontuacao, pontuacao, tempo_jogo) values (164, 1, 1, 3);
insert into pontuacoes (id_pontuacao, id_tipo_pontuacao, pontuacao, tempo_jogo) values (165, 1, 1, 10);
insert into pontuacoes (id_pontuacao, id_tipo_pontuacao, pontuacao, tempo_jogo) values (166, 1, 1, 12);
insert into pontuacoes (id_pontuacao, id_tipo_pontuacao, pontuacao, tempo_jogo) values (167, 1, 1, 19);
insert into pontuacoes (id_pontuacao, id_tipo_pontuacao, pontuacao, tempo_jogo) values (168, 1, 1, 25);
insert into pontuacoes (id_pontuacao, id_tipo_pontuacao, pontuacao, tempo_jogo) values (169, 1, 1, 11);
insert into pontuacoes (id_pontuacao, id_tipo_pontuacao, pontuacao, tempo_jogo) values (170, 1, 1, 8);
insert into pontuacoes (id_pontuacao, id_tipo_pontuacao, pontuacao, tempo_jogo) values (171, 1, 1, 14);
insert into pontuacoes (id_pontuacao, id_tipo_pontuacao, pontuacao, tempo_jogo) values (172, 1, 1, 12);
insert into pontuacoes (id_pontuacao, id_tipo_pontuacao, pontuacao, tempo_jogo) values (173, 1, 1, 30);
insert into pontuacoes (id_pontuacao, id_tipo_pontuacao, pontuacao, tempo_jogo) values (174, 1, 1, 4);
insert into pontuacoes (id_pontuacao, id_tipo_pontuacao, pontuacao, tempo_jogo) values (175, 1, 1, 22);
insert into pontuacoes (id_pontuacao, id_tipo_pontuacao, pontuacao, tempo_jogo) values (176, 1, 1, 7);
insert into pontuacoes (id_pontuacao, id_tipo_pontuacao, pontuacao, tempo_jogo) values (177, 1, 1, 32);
insert into pontuacoes (id_pontuacao, id_tipo_pontuacao, pontuacao, tempo_jogo) values (178, 1, 1, 23);
insert into pontuacoes (id_pontuacao, id_tipo_pontuacao, pontuacao, tempo_jogo) values (179, 1, 1, 30);
insert into pontuacoes (id_pontuacao, id_tipo_pontuacao, pontuacao, tempo_jogo) values (180, 1, 1, 8);
insert into pontuacoes (id_pontuacao, id_tipo_pontuacao, pontuacao, tempo_jogo) values (181, 1, 1, 26);
insert into pontuacoes (id_pontuacao, id_tipo_pontuacao, pontuacao, tempo_jogo) values (182, 1, 1, 13);
insert into pontuacoes (id_pontuacao, id_tipo_pontuacao, pontuacao, tempo_jogo) values (183, 1, 1, 30);
insert into pontuacoes (id_pontuacao, id_tipo_pontuacao, pontuacao, tempo_jogo) values (184, 1, 1, 17);
insert into pontuacoes (id_pontuacao, id_tipo_pontuacao, pontuacao, tempo_jogo) values (185, 1, 1, 3);
insert into pontuacoes (id_pontuacao, id_tipo_pontuacao, pontuacao, tempo_jogo) values (186, 1, 1, 38);
insert into pontuacoes (id_pontuacao, id_tipo_pontuacao, pontuacao, tempo_jogo) values (187, 1, 1, 24);
insert into pontuacoes (id_pontuacao, id_tipo_pontuacao, pontuacao, tempo_jogo) values (188, 1, 1, 12);
insert into pontuacoes (id_pontuacao, id_tipo_pontuacao, pontuacao, tempo_jogo) values (189, 1, 1, 13);
insert into pontuacoes (id_pontuacao, id_tipo_pontuacao, pontuacao, tempo_jogo) values (190, 1, 1, 19);
insert into pontuacoes (id_pontuacao, id_tipo_pontuacao, pontuacao, tempo_jogo) values (191, 1, 1, 19);
insert into pontuacoes (id_pontuacao, id_tipo_pontuacao, pontuacao, tempo_jogo) values (192, 1, 1, 25);
insert into pontuacoes (id_pontuacao, id_tipo_pontuacao, pontuacao, tempo_jogo) values (193, 1, 1, 3);
insert into pontuacoes (id_pontuacao, id_tipo_pontuacao, pontuacao, tempo_jogo) values (194, 1, 1, 28);
insert into pontuacoes (id_pontuacao, id_tipo_pontuacao, pontuacao, tempo_jogo) values (195, 1, 1, 6);
insert into pontuacoes (id_pontuacao, id_tipo_pontuacao, pontuacao, tempo_jogo) values (196, 1, 1, 26);
insert into pontuacoes (id_pontuacao, id_tipo_pontuacao, pontuacao, tempo_jogo) values (197, 1, 1, 11);
insert into pontuacoes (id_pontuacao, id_tipo_pontuacao, pontuacao, tempo_jogo) values (198, 1, 1, 15);
insert into pontuacoes (id_pontuacao, id_tipo_pontuacao, pontuacao, tempo_jogo) values (199, 1, 1, 26);
insert into pontuacoes (id_pontuacao, id_tipo_pontuacao, pontuacao, tempo_jogo) values (200, 1, 1, 26);
insert into pontuacoes (id_pontuacao, id_tipo_pontuacao, pontuacao, tempo_jogo) values (201, 2, 2, 29);
insert into pontuacoes (id_pontuacao, id_tipo_pontuacao, pontuacao, tempo_jogo) values (202, 2, 1, 24);
insert into pontuacoes (id_pontuacao, id_tipo_pontuacao, pontuacao, tempo_jogo) values (203, 2, 3, 26);
insert into pontuacoes (id_pontuacao, id_tipo_pontuacao, pontuacao, tempo_jogo) values (204, 2, 3, 1);
insert into pontuacoes (id_pontuacao, id_tipo_pontuacao, pontuacao, tempo_jogo) values (205, 2, 2, 10);
insert into pontuacoes (id_pontuacao, id_tipo_pontuacao, pontuacao, tempo_jogo) values (206, 2, 2, 36);
insert into pontuacoes (id_pontuacao, id_tipo_pontuacao, pontuacao, tempo_jogo) values (207, 2, 1, 35);
insert into pontuacoes (id_pontuacao, id_tipo_pontuacao, pontuacao, tempo_jogo) values (208, 2, 3, 38);
insert into pontuacoes (id_pontuacao, id_tipo_pontuacao, pontuacao, tempo_jogo) values (209, 2, 1, 21);
insert into pontuacoes (id_pontuacao, id_tipo_pontuacao, pontuacao, tempo_jogo) values (210, 2, 1, 38);
insert into pontuacoes (id_pontuacao, id_tipo_pontuacao, pontuacao, tempo_jogo) values (211, 2, 2, 7);
insert into pontuacoes (id_pontuacao, id_tipo_pontuacao, pontuacao, tempo_jogo) values (212, 2, 1, 30);
insert into pontuacoes (id_pontuacao, id_tipo_pontuacao, pontuacao, tempo_jogo) values (213, 2, 3, 28);
insert into pontuacoes (id_pontuacao, id_tipo_pontuacao, pontuacao, tempo_jogo) values (214, 2, 1, 14);
insert into pontuacoes (id_pontuacao, id_tipo_pontuacao, pontuacao, tempo_jogo) values (215, 2, 2, 10);
insert into pontuacoes (id_pontuacao, id_tipo_pontuacao, pontuacao, tempo_jogo) values (216, 2, 1, 35);
insert into pontuacoes (id_pontuacao, id_tipo_pontuacao, pontuacao, tempo_jogo) values (217, 2, 2, 37);
insert into pontuacoes (id_pontuacao, id_tipo_pontuacao, pontuacao, tempo_jogo) values (218, 2, 3, 18);
insert into pontuacoes (id_pontuacao, id_tipo_pontuacao, pontuacao, tempo_jogo) values (219, 2, 1, 39);
insert into pontuacoes (id_pontuacao, id_tipo_pontuacao, pontuacao, tempo_jogo) values (220, 2, 1, 11);
insert into pontuacoes (id_pontuacao, id_tipo_pontuacao, pontuacao, tempo_jogo) values (221, 2, 1, 9);
insert into pontuacoes (id_pontuacao, id_tipo_pontuacao, pontuacao, tempo_jogo) values (222, 2, 3, 3);
insert into pontuacoes (id_pontuacao, id_tipo_pontuacao, pontuacao, tempo_jogo) values (223, 2, 3, 2);
insert into pontuacoes (id_pontuacao, id_tipo_pontuacao, pontuacao, tempo_jogo) values (224, 2, 3, 17);
insert into pontuacoes (id_pontuacao, id_tipo_pontuacao, pontuacao, tempo_jogo) values (225, 2, 3, 6);
insert into pontuacoes (id_pontuacao, id_tipo_pontuacao, pontuacao, tempo_jogo) values (226, 2, 1, 18);
insert into pontuacoes (id_pontuacao, id_tipo_pontuacao, pontuacao, tempo_jogo) values (227, 2, 2, 7);
insert into pontuacoes (id_pontuacao, id_tipo_pontuacao, pontuacao, tempo_jogo) values (228, 2, 1, 22);
insert into pontuacoes (id_pontuacao, id_tipo_pontuacao, pontuacao, tempo_jogo) values (229, 2, 1, 27);
insert into pontuacoes (id_pontuacao, id_tipo_pontuacao, pontuacao, tempo_jogo) values (230, 2, 1, 26);
insert into pontuacoes (id_pontuacao, id_tipo_pontuacao, pontuacao, tempo_jogo) values (231, 2, 1, 11);
insert into pontuacoes (id_pontuacao, id_tipo_pontuacao, pontuacao, tempo_jogo) values (232, 2, 2, 26);
insert into pontuacoes (id_pontuacao, id_tipo_pontuacao, pontuacao, tempo_jogo) values (233, 2, 3, 1);
insert into pontuacoes (id_pontuacao, id_tipo_pontuacao, pontuacao, tempo_jogo) values (234, 2, 3, 17);
insert into pontuacoes (id_pontuacao, id_tipo_pontuacao, pontuacao, tempo_jogo) values (235, 2, 2, 19);
insert into pontuacoes (id_pontuacao, id_tipo_pontuacao, pontuacao, tempo_jogo) values (236, 2, 2, 7);
insert into pontuacoes (id_pontuacao, id_tipo_pontuacao, pontuacao, tempo_jogo) values (237, 2, 2, 19);
insert into pontuacoes (id_pontuacao, id_tipo_pontuacao, pontuacao, tempo_jogo) values (238, 2, 1, 28);
insert into pontuacoes (id_pontuacao, id_tipo_pontuacao, pontuacao, tempo_jogo) values (239, 2, 2, 29);
insert into pontuacoes (id_pontuacao, id_tipo_pontuacao, pontuacao, tempo_jogo) values (240, 2, 3, 5);
insert into pontuacoes (id_pontuacao, id_tipo_pontuacao, pontuacao, tempo_jogo) values (241, 2, 2, 11);
insert into pontuacoes (id_pontuacao, id_tipo_pontuacao, pontuacao, tempo_jogo) values (242, 2, 2, 16);
insert into pontuacoes (id_pontuacao, id_tipo_pontuacao, pontuacao, tempo_jogo) values (243, 2, 3, 20);
insert into pontuacoes (id_pontuacao, id_tipo_pontuacao, pontuacao, tempo_jogo) values (244, 2, 2, 2);
insert into pontuacoes (id_pontuacao, id_tipo_pontuacao, pontuacao, tempo_jogo) values (245, 2, 3, 22);
insert into pontuacoes (id_pontuacao, id_tipo_pontuacao, pontuacao, tempo_jogo) values (246, 2, 3, 23);
insert into pontuacoes (id_pontuacao, id_tipo_pontuacao, pontuacao, tempo_jogo) values (247, 2, 3, 9);
insert into pontuacoes (id_pontuacao, id_tipo_pontuacao, pontuacao, tempo_jogo) values (248, 2, 3, 7);
insert into pontuacoes (id_pontuacao, id_tipo_pontuacao, pontuacao, tempo_jogo) values (249, 2, 2, 9);
insert into pontuacoes (id_pontuacao, id_tipo_pontuacao, pontuacao, tempo_jogo) values (250, 2, 1, 12);
insert into pontuacoes (id_pontuacao, id_tipo_pontuacao, pontuacao, tempo_jogo) values (251, 2, 2, 6);
insert into pontuacoes (id_pontuacao, id_tipo_pontuacao, pontuacao, tempo_jogo) values (252, 2, 3, 16);
insert into pontuacoes (id_pontuacao, id_tipo_pontuacao, pontuacao, tempo_jogo) values (253, 2, 2, 26);
insert into pontuacoes (id_pontuacao, id_tipo_pontuacao, pontuacao, tempo_jogo) values (254, 2, 1, 21);
insert into pontuacoes (id_pontuacao, id_tipo_pontuacao, pontuacao, tempo_jogo) values (255, 2, 1, 12);
insert into pontuacoes (id_pontuacao, id_tipo_pontuacao, pontuacao, tempo_jogo) values (256, 2, 2, 27);
insert into pontuacoes (id_pontuacao, id_tipo_pontuacao, pontuacao, tempo_jogo) values (257, 2, 1, 37);
insert into pontuacoes (id_pontuacao, id_tipo_pontuacao, pontuacao, tempo_jogo) values (258, 2, 2, 17);
insert into pontuacoes (id_pontuacao, id_tipo_pontuacao, pontuacao, tempo_jogo) values (259, 2, 3, 2);
insert into pontuacoes (id_pontuacao, id_tipo_pontuacao, pontuacao, tempo_jogo) values (260, 2, 1, 33);
insert into pontuacoes (id_pontuacao, id_tipo_pontuacao, pontuacao, tempo_jogo) values (261, 2, 3, 33);
insert into pontuacoes (id_pontuacao, id_tipo_pontuacao, pontuacao, tempo_jogo) values (262, 2, 2, 26);
insert into pontuacoes (id_pontuacao, id_tipo_pontuacao, pontuacao, tempo_jogo) values (263, 2, 1, 30);
insert into pontuacoes (id_pontuacao, id_tipo_pontuacao, pontuacao, tempo_jogo) values (264, 2, 3, 37);
insert into pontuacoes (id_pontuacao, id_tipo_pontuacao, pontuacao, tempo_jogo) values (265, 2, 3, 18);
insert into pontuacoes (id_pontuacao, id_tipo_pontuacao, pontuacao, tempo_jogo) values (266, 2, 1, 16);
insert into pontuacoes (id_pontuacao, id_tipo_pontuacao, pontuacao, tempo_jogo) values (267, 2, 1, 32);
insert into pontuacoes (id_pontuacao, id_tipo_pontuacao, pontuacao, tempo_jogo) values (268, 2, 3, 15);
insert into pontuacoes (id_pontuacao, id_tipo_pontuacao, pontuacao, tempo_jogo) values (269, 2, 3, 18);
insert into pontuacoes (id_pontuacao, id_tipo_pontuacao, pontuacao, tempo_jogo) values (270, 2, 2, 34);
insert into pontuacoes (id_pontuacao, id_tipo_pontuacao, pontuacao, tempo_jogo) values (271, 2, 3, 28);
insert into pontuacoes (id_pontuacao, id_tipo_pontuacao, pontuacao, tempo_jogo) values (272, 2, 1, 5);
insert into pontuacoes (id_pontuacao, id_tipo_pontuacao, pontuacao, tempo_jogo) values (273, 2, 2, 31);
insert into pontuacoes (id_pontuacao, id_tipo_pontuacao, pontuacao, tempo_jogo) values (274, 2, 2, 36);
insert into pontuacoes (id_pontuacao, id_tipo_pontuacao, pontuacao, tempo_jogo) values (275, 2, 1, 13);
insert into pontuacoes (id_pontuacao, id_tipo_pontuacao, pontuacao, tempo_jogo) values (276, 2, 1, 31);
insert into pontuacoes (id_pontuacao, id_tipo_pontuacao, pontuacao, tempo_jogo) values (277, 2, 3, 37);
insert into pontuacoes (id_pontuacao, id_tipo_pontuacao, pontuacao, tempo_jogo) values (278, 2, 2, 40);
insert into pontuacoes (id_pontuacao, id_tipo_pontuacao, pontuacao, tempo_jogo) values (279, 2, 1, 21);
insert into pontuacoes (id_pontuacao, id_tipo_pontuacao, pontuacao, tempo_jogo) values (280, 2, 2, 26);
insert into pontuacoes (id_pontuacao, id_tipo_pontuacao, pontuacao, tempo_jogo) values (281, 2, 3, 30);
insert into pontuacoes (id_pontuacao, id_tipo_pontuacao, pontuacao, tempo_jogo) values (282, 2, 3, 7);
insert into pontuacoes (id_pontuacao, id_tipo_pontuacao, pontuacao, tempo_jogo) values (283, 2, 2, 22);
insert into pontuacoes (id_pontuacao, id_tipo_pontuacao, pontuacao, tempo_jogo) values (284, 2, 1, 33);
insert into pontuacoes (id_pontuacao, id_tipo_pontuacao, pontuacao, tempo_jogo) values (285, 2, 3, 27);
insert into pontuacoes (id_pontuacao, id_tipo_pontuacao, pontuacao, tempo_jogo) values (286, 2, 2, 27);
insert into pontuacoes (id_pontuacao, id_tipo_pontuacao, pontuacao, tempo_jogo) values (287, 2, 2, 36);
insert into pontuacoes (id_pontuacao, id_tipo_pontuacao, pontuacao, tempo_jogo) values (288, 2, 3, 11);
insert into pontuacoes (id_pontuacao, id_tipo_pontuacao, pontuacao, tempo_jogo) values (289, 2, 3, 5);
insert into pontuacoes (id_pontuacao, id_tipo_pontuacao, pontuacao, tempo_jogo) values (290, 2, 3, 10);
insert into pontuacoes (id_pontuacao, id_tipo_pontuacao, pontuacao, tempo_jogo) values (291, 2, 1, 25);
insert into pontuacoes (id_pontuacao, id_tipo_pontuacao, pontuacao, tempo_jogo) values (292, 2, 1, 3);
insert into pontuacoes (id_pontuacao, id_tipo_pontuacao, pontuacao, tempo_jogo) values (293, 2, 1, 8);
insert into pontuacoes (id_pontuacao, id_tipo_pontuacao, pontuacao, tempo_jogo) values (294, 2, 2, 32);
insert into pontuacoes (id_pontuacao, id_tipo_pontuacao, pontuacao, tempo_jogo) values (295, 2, 3, 10);
insert into pontuacoes (id_pontuacao, id_tipo_pontuacao, pontuacao, tempo_jogo) values (296, 2, 1, 35);
insert into pontuacoes (id_pontuacao, id_tipo_pontuacao, pontuacao, tempo_jogo) values (297, 2, 2, 18);
insert into pontuacoes (id_pontuacao, id_tipo_pontuacao, pontuacao, tempo_jogo) values (298, 2, 1, 17);
insert into pontuacoes (id_pontuacao, id_tipo_pontuacao, pontuacao, tempo_jogo) values (299, 2, 3, 27);
insert into pontuacoes (id_pontuacao, id_tipo_pontuacao, pontuacao, tempo_jogo) values (300, 2, 2, 27);
insert into pontuacoes (id_pontuacao, id_tipo_pontuacao, pontuacao, tempo_jogo) values (301, 2, 3, 19);
insert into pontuacoes (id_pontuacao, id_tipo_pontuacao, pontuacao, tempo_jogo) values (302, 2, 3, 3);
insert into pontuacoes (id_pontuacao, id_tipo_pontuacao, pontuacao, tempo_jogo) values (303, 2, 3, 17);
insert into pontuacoes (id_pontuacao, id_tipo_pontuacao, pontuacao, tempo_jogo) values (304, 2, 3, 17);
insert into pontuacoes (id_pontuacao, id_tipo_pontuacao, pontuacao, tempo_jogo) values (305, 2, 3, 21);
insert into pontuacoes (id_pontuacao, id_tipo_pontuacao, pontuacao, tempo_jogo) values (306, 2, 3, 14);
insert into pontuacoes (id_pontuacao, id_tipo_pontuacao, pontuacao, tempo_jogo) values (307, 2, 3, 26);
insert into pontuacoes (id_pontuacao, id_tipo_pontuacao, pontuacao, tempo_jogo) values (308, 2, 3, 40);
insert into pontuacoes (id_pontuacao, id_tipo_pontuacao, pontuacao, tempo_jogo) values (309, 2, 2, 30);
insert into pontuacoes (id_pontuacao, id_tipo_pontuacao, pontuacao, tempo_jogo) values (310, 2, 2, 28);
insert into pontuacoes (id_pontuacao, id_tipo_pontuacao, pontuacao, tempo_jogo) values (311, 2, 1, 5);
insert into pontuacoes (id_pontuacao, id_tipo_pontuacao, pontuacao, tempo_jogo) values (312, 2, 3, 11);
insert into pontuacoes (id_pontuacao, id_tipo_pontuacao, pontuacao, tempo_jogo) values (313, 2, 3, 14);
insert into pontuacoes (id_pontuacao, id_tipo_pontuacao, pontuacao, tempo_jogo) values (314, 2, 2, 19);
insert into pontuacoes (id_pontuacao, id_tipo_pontuacao, pontuacao, tempo_jogo) values (315, 2, 3, 27);
insert into pontuacoes (id_pontuacao, id_tipo_pontuacao, pontuacao, tempo_jogo) values (316, 2, 3, 1);
insert into pontuacoes (id_pontuacao, id_tipo_pontuacao, pontuacao, tempo_jogo) values (317, 2, 1, 3);
insert into pontuacoes (id_pontuacao, id_tipo_pontuacao, pontuacao, tempo_jogo) values (318, 2, 2, 27);
insert into pontuacoes (id_pontuacao, id_tipo_pontuacao, pontuacao, tempo_jogo) values (319, 2, 2, 17);
insert into pontuacoes (id_pontuacao, id_tipo_pontuacao, pontuacao, tempo_jogo) values (320, 2, 2, 11);
insert into pontuacoes (id_pontuacao, id_tipo_pontuacao, pontuacao, tempo_jogo) values (321, 2, 1, 35);
insert into pontuacoes (id_pontuacao, id_tipo_pontuacao, pontuacao, tempo_jogo) values (322, 2, 2, 37);
insert into pontuacoes (id_pontuacao, id_tipo_pontuacao, pontuacao, tempo_jogo) values (323, 2, 2, 1);
insert into pontuacoes (id_pontuacao, id_tipo_pontuacao, pontuacao, tempo_jogo) values (324, 2, 1, 33);
insert into pontuacoes (id_pontuacao, id_tipo_pontuacao, pontuacao, tempo_jogo) values (325, 2, 1, 15);
insert into pontuacoes (id_pontuacao, id_tipo_pontuacao, pontuacao, tempo_jogo) values (326, 2, 2, 35);
insert into pontuacoes (id_pontuacao, id_tipo_pontuacao, pontuacao, tempo_jogo) values (327, 2, 2, 31);
insert into pontuacoes (id_pontuacao, id_tipo_pontuacao, pontuacao, tempo_jogo) values (328, 2, 1, 21);
insert into pontuacoes (id_pontuacao, id_tipo_pontuacao, pontuacao, tempo_jogo) values (329, 2, 1, 18);
insert into pontuacoes (id_pontuacao, id_tipo_pontuacao, pontuacao, tempo_jogo) values (330, 2, 2, 40);
insert into pontuacoes (id_pontuacao, id_tipo_pontuacao, pontuacao, tempo_jogo) values (331, 2, 3, 15);
insert into pontuacoes (id_pontuacao, id_tipo_pontuacao, pontuacao, tempo_jogo) values (332, 2, 2, 13);
insert into pontuacoes (id_pontuacao, id_tipo_pontuacao, pontuacao, tempo_jogo) values (333, 2, 2, 15);
insert into pontuacoes (id_pontuacao, id_tipo_pontuacao, pontuacao, tempo_jogo) values (334, 2, 1, 28);
insert into pontuacoes (id_pontuacao, id_tipo_pontuacao, pontuacao, tempo_jogo) values (335, 2, 1, 20);
insert into pontuacoes (id_pontuacao, id_tipo_pontuacao, pontuacao, tempo_jogo) values (336, 2, 3, 33);
insert into pontuacoes (id_pontuacao, id_tipo_pontuacao, pontuacao, tempo_jogo) values (337, 2, 3, 6);
insert into pontuacoes (id_pontuacao, id_tipo_pontuacao, pontuacao, tempo_jogo) values (338, 2, 2, 3);
insert into pontuacoes (id_pontuacao, id_tipo_pontuacao, pontuacao, tempo_jogo) values (339, 2, 3, 25);
insert into pontuacoes (id_pontuacao, id_tipo_pontuacao, pontuacao, tempo_jogo) values (340, 2, 3, 29);
insert into pontuacoes (id_pontuacao, id_tipo_pontuacao, pontuacao, tempo_jogo) values (341, 2, 3, 22);
insert into pontuacoes (id_pontuacao, id_tipo_pontuacao, pontuacao, tempo_jogo) values (342, 2, 3, 16);
insert into pontuacoes (id_pontuacao, id_tipo_pontuacao, pontuacao, tempo_jogo) values (343, 2, 2, 24);
insert into pontuacoes (id_pontuacao, id_tipo_pontuacao, pontuacao, tempo_jogo) values (344, 2, 2, 15);
insert into pontuacoes (id_pontuacao, id_tipo_pontuacao, pontuacao, tempo_jogo) values (345, 2, 1, 5);
insert into pontuacoes (id_pontuacao, id_tipo_pontuacao, pontuacao, tempo_jogo) values (346, 2, 2, 5);
insert into pontuacoes (id_pontuacao, id_tipo_pontuacao, pontuacao, tempo_jogo) values (347, 2, 2, 20);
insert into pontuacoes (id_pontuacao, id_tipo_pontuacao, pontuacao, tempo_jogo) values (348, 2, 2, 34);
insert into pontuacoes (id_pontuacao, id_tipo_pontuacao, pontuacao, tempo_jogo) values (349, 2, 3, 2);
insert into pontuacoes (id_pontuacao, id_tipo_pontuacao, pontuacao, tempo_jogo) values (350, 2, 1, 35);
insert into pontuacoes (id_pontuacao, id_tipo_pontuacao, pontuacao, tempo_jogo) values (351, 2, 2, 31);
insert into pontuacoes (id_pontuacao, id_tipo_pontuacao, pontuacao, tempo_jogo) values (352, 2, 3, 3);
insert into pontuacoes (id_pontuacao, id_tipo_pontuacao, pontuacao, tempo_jogo) values (353, 2, 3, 28);
insert into pontuacoes (id_pontuacao, id_tipo_pontuacao, pontuacao, tempo_jogo) values (354, 2, 3, 15);
insert into pontuacoes (id_pontuacao, id_tipo_pontuacao, pontuacao, tempo_jogo) values (355, 2, 2, 1);
insert into pontuacoes (id_pontuacao, id_tipo_pontuacao, pontuacao, tempo_jogo) values (356, 2, 3, 32);
insert into pontuacoes (id_pontuacao, id_tipo_pontuacao, pontuacao, tempo_jogo) values (357, 2, 3, 17);
insert into pontuacoes (id_pontuacao, id_tipo_pontuacao, pontuacao, tempo_jogo) values (358, 2, 1, 38);
insert into pontuacoes (id_pontuacao, id_tipo_pontuacao, pontuacao, tempo_jogo) values (359, 2, 1, 1);
insert into pontuacoes (id_pontuacao, id_tipo_pontuacao, pontuacao, tempo_jogo) values (360, 2, 2, 15);
insert into pontuacoes (id_pontuacao, id_tipo_pontuacao, pontuacao, tempo_jogo) values (361, 2, 1, 11);
insert into pontuacoes (id_pontuacao, id_tipo_pontuacao, pontuacao, tempo_jogo) values (362, 2, 2, 27);
insert into pontuacoes (id_pontuacao, id_tipo_pontuacao, pontuacao, tempo_jogo) values (363, 2, 3, 20);
insert into pontuacoes (id_pontuacao, id_tipo_pontuacao, pontuacao, tempo_jogo) values (364, 2, 1, 28);
insert into pontuacoes (id_pontuacao, id_tipo_pontuacao, pontuacao, tempo_jogo) values (365, 2, 1, 5);
insert into pontuacoes (id_pontuacao, id_tipo_pontuacao, pontuacao, tempo_jogo) values (366, 2, 1, 4);
insert into pontuacoes (id_pontuacao, id_tipo_pontuacao, pontuacao, tempo_jogo) values (367, 2, 3, 18);
insert into pontuacoes (id_pontuacao, id_tipo_pontuacao, pontuacao, tempo_jogo) values (368, 2, 3, 1);
insert into pontuacoes (id_pontuacao, id_tipo_pontuacao, pontuacao, tempo_jogo) values (369, 2, 3, 33);
insert into pontuacoes (id_pontuacao, id_tipo_pontuacao, pontuacao, tempo_jogo) values (370, 2, 3, 40);
insert into pontuacoes (id_pontuacao, id_tipo_pontuacao, pontuacao, tempo_jogo) values (371, 2, 2, 21);
insert into pontuacoes (id_pontuacao, id_tipo_pontuacao, pontuacao, tempo_jogo) values (372, 2, 2, 33);
insert into pontuacoes (id_pontuacao, id_tipo_pontuacao, pontuacao, tempo_jogo) values (373, 2, 3, 16);
insert into pontuacoes (id_pontuacao, id_tipo_pontuacao, pontuacao, tempo_jogo) values (374, 2, 1, 19);
insert into pontuacoes (id_pontuacao, id_tipo_pontuacao, pontuacao, tempo_jogo) values (375, 2, 2, 32);
insert into pontuacoes (id_pontuacao, id_tipo_pontuacao, pontuacao, tempo_jogo) values (376, 2, 2, 30);
insert into pontuacoes (id_pontuacao, id_tipo_pontuacao, pontuacao, tempo_jogo) values (377, 2, 1, 31);
insert into pontuacoes (id_pontuacao, id_tipo_pontuacao, pontuacao, tempo_jogo) values (378, 2, 1, 12);
insert into pontuacoes (id_pontuacao, id_tipo_pontuacao, pontuacao, tempo_jogo) values (379, 2, 1, 24);
insert into pontuacoes (id_pontuacao, id_tipo_pontuacao, pontuacao, tempo_jogo) values (380, 2, 2, 19);
insert into pontuacoes (id_pontuacao, id_tipo_pontuacao, pontuacao, tempo_jogo) values (381, 2, 3, 7);
insert into pontuacoes (id_pontuacao, id_tipo_pontuacao, pontuacao, tempo_jogo) values (382, 2, 1, 10);
insert into pontuacoes (id_pontuacao, id_tipo_pontuacao, pontuacao, tempo_jogo) values (383, 2, 3, 6);
insert into pontuacoes (id_pontuacao, id_tipo_pontuacao, pontuacao, tempo_jogo) values (384, 2, 2, 4);
insert into pontuacoes (id_pontuacao, id_tipo_pontuacao, pontuacao, tempo_jogo) values (385, 2, 3, 27);
insert into pontuacoes (id_pontuacao, id_tipo_pontuacao, pontuacao, tempo_jogo) values (386, 2, 3, 12);
insert into pontuacoes (id_pontuacao, id_tipo_pontuacao, pontuacao, tempo_jogo) values (387, 2, 1, 24);
insert into pontuacoes (id_pontuacao, id_tipo_pontuacao, pontuacao, tempo_jogo) values (388, 2, 2, 29);
insert into pontuacoes (id_pontuacao, id_tipo_pontuacao, pontuacao, tempo_jogo) values (389, 2, 3, 30);
insert into pontuacoes (id_pontuacao, id_tipo_pontuacao, pontuacao, tempo_jogo) values (390, 2, 3, 39);
insert into pontuacoes (id_pontuacao, id_tipo_pontuacao, pontuacao, tempo_jogo) values (391, 2, 3, 31);
insert into pontuacoes (id_pontuacao, id_tipo_pontuacao, pontuacao, tempo_jogo) values (392, 2, 2, 9);
insert into pontuacoes (id_pontuacao, id_tipo_pontuacao, pontuacao, tempo_jogo) values (393, 2, 1, 7);
insert into pontuacoes (id_pontuacao, id_tipo_pontuacao, pontuacao, tempo_jogo) values (394, 2, 1, 6);
insert into pontuacoes (id_pontuacao, id_tipo_pontuacao, pontuacao, tempo_jogo) values (395, 2, 1, 1);
insert into pontuacoes (id_pontuacao, id_tipo_pontuacao, pontuacao, tempo_jogo) values (396, 2, 3, 31);
insert into pontuacoes (id_pontuacao, id_tipo_pontuacao, pontuacao, tempo_jogo) values (397, 2, 1, 15);
insert into pontuacoes (id_pontuacao, id_tipo_pontuacao, pontuacao, tempo_jogo) values (398, 2, 3, 32);
insert into pontuacoes (id_pontuacao, id_tipo_pontuacao, pontuacao, tempo_jogo) values (399, 2, 2, 23);
insert into pontuacoes (id_pontuacao, id_tipo_pontuacao, pontuacao, tempo_jogo) values (400, 2, 1, 15);
insert into pontuacoes (id_pontuacao, id_tipo_pontuacao, pontuacao, tempo_jogo) values (401, 2, 1, 0);
insert into pontuacoes (id_pontuacao, id_tipo_pontuacao, pontuacao, tempo_jogo) values (402, 2, 1, 0);
insert into pontuacoes (id_pontuacao, id_tipo_pontuacao, pontuacao, tempo_jogo) values (403, 2, 1, 0);
insert into pontuacoes (id_pontuacao, id_tipo_pontuacao, pontuacao, tempo_jogo) values (404, 2, 1, 0);
insert into pontuacoes (id_pontuacao, id_tipo_pontuacao, pontuacao, tempo_jogo) values (405, 2, 1, 0);
insert into pontuacoes (id_pontuacao, id_tipo_pontuacao, pontuacao, tempo_jogo) values (406, 2, 1, 0);
insert into pontuacoes (id_pontuacao, id_tipo_pontuacao, pontuacao, tempo_jogo) values (407, 2, 1, 0);
insert into pontuacoes (id_pontuacao, id_tipo_pontuacao, pontuacao, tempo_jogo) values (408, 2, 1, 0);
insert into pontuacoes (id_pontuacao, id_tipo_pontuacao, pontuacao, tempo_jogo) values (409, 2, 1, 0);
insert into pontuacoes (id_pontuacao, id_tipo_pontuacao, pontuacao, tempo_jogo) values (410, 2, 1, 0);
insert into pontuacoes (id_pontuacao, id_tipo_pontuacao, pontuacao, tempo_jogo) values (411, 2, 1, 0);
insert into pontuacoes (id_pontuacao, id_tipo_pontuacao, pontuacao, tempo_jogo) values (412, 2, 1, 0);
insert into pontuacoes (id_pontuacao, id_tipo_pontuacao, pontuacao, tempo_jogo) values (413, 2, 1, 0);
insert into pontuacoes (id_pontuacao, id_tipo_pontuacao, pontuacao, tempo_jogo) values (414, 2, 1, 0);
insert into pontuacoes (id_pontuacao, id_tipo_pontuacao, pontuacao, tempo_jogo) values (415, 2, 1, 0);
insert into pontuacoes (id_pontuacao, id_tipo_pontuacao, pontuacao, tempo_jogo) values (416, 2, 1, 0);
insert into pontuacoes (id_pontuacao, id_tipo_pontuacao, pontuacao, tempo_jogo) values (417, 2, 1, 0);
insert into pontuacoes (id_pontuacao, id_tipo_pontuacao, pontuacao, tempo_jogo) values (418, 2, 1, 0);
insert into pontuacoes (id_pontuacao, id_tipo_pontuacao, pontuacao, tempo_jogo) values (419, 2, 1, 0);
insert into pontuacoes (id_pontuacao, id_tipo_pontuacao, pontuacao, tempo_jogo) values (420, 2, 1, 0);
insert into pontuacoes (id_pontuacao, id_tipo_pontuacao, pontuacao, tempo_jogo) values (421, 2, 1, 0);
insert into pontuacoes (id_pontuacao, id_tipo_pontuacao, pontuacao, tempo_jogo) values (422, 2, 1, 0);
insert into pontuacoes (id_pontuacao, id_tipo_pontuacao, pontuacao, tempo_jogo) values (423, 2, 1, 0);
insert into pontuacoes (id_pontuacao, id_tipo_pontuacao, pontuacao, tempo_jogo) values (424, 2, 1, 0);
insert into pontuacoes (id_pontuacao, id_tipo_pontuacao, pontuacao, tempo_jogo) values (425, 2, 1, 0);
insert into pontuacoes (id_pontuacao, id_tipo_pontuacao, pontuacao, tempo_jogo) values (426, 2, 1, 0);
insert into pontuacoes (id_pontuacao, id_tipo_pontuacao, pontuacao, tempo_jogo) values (427, 2, 1, 0);
insert into pontuacoes (id_pontuacao, id_tipo_pontuacao, pontuacao, tempo_jogo) values (428, 2, 1, 0);
insert into pontuacoes (id_pontuacao, id_tipo_pontuacao, pontuacao, tempo_jogo) values (429, 2, 1, 0);
insert into pontuacoes (id_pontuacao, id_tipo_pontuacao, pontuacao, tempo_jogo) values (430, 2, 1, 0);
insert into pontuacoes (id_pontuacao, id_tipo_pontuacao, pontuacao, tempo_jogo) values (431, 2, 1, 0);
insert into pontuacoes (id_pontuacao, id_tipo_pontuacao, pontuacao, tempo_jogo) values (432, 2, 1, 0);
insert into pontuacoes (id_pontuacao, id_tipo_pontuacao, pontuacao, tempo_jogo) values (433, 2, 1, 0);
insert into pontuacoes (id_pontuacao, id_tipo_pontuacao, pontuacao, tempo_jogo) values (434, 2, 1, 0);
insert into pontuacoes (id_pontuacao, id_tipo_pontuacao, pontuacao, tempo_jogo) values (435, 2, 1, 0);
insert into pontuacoes (id_pontuacao, id_tipo_pontuacao, pontuacao, tempo_jogo) values (436, 2, 1, 0);
insert into pontuacoes (id_pontuacao, id_tipo_pontuacao, pontuacao, tempo_jogo) values (437, 2, 1, 0);
insert into pontuacoes (id_pontuacao, id_tipo_pontuacao, pontuacao, tempo_jogo) values (438, 2, 1, 0);
insert into pontuacoes (id_pontuacao, id_tipo_pontuacao, pontuacao, tempo_jogo) values (439, 2, 1, 0);
insert into pontuacoes (id_pontuacao, id_tipo_pontuacao, pontuacao, tempo_jogo) values (440, 2, 1, 0);
insert into pontuacoes (id_pontuacao, id_tipo_pontuacao, pontuacao, tempo_jogo) values (441, 2, 1, 0);
insert into pontuacoes (id_pontuacao, id_tipo_pontuacao, pontuacao, tempo_jogo) values (442, 2, 1, 0);
insert into pontuacoes (id_pontuacao, id_tipo_pontuacao, pontuacao, tempo_jogo) values (443, 2, 1, 0);
insert into pontuacoes (id_pontuacao, id_tipo_pontuacao, pontuacao, tempo_jogo) values (444, 2, 1, 0);
insert into pontuacoes (id_pontuacao, id_tipo_pontuacao, pontuacao, tempo_jogo) values (445, 2, 1, 0);
insert into pontuacoes (id_pontuacao, id_tipo_pontuacao, pontuacao, tempo_jogo) values (446, 2, 1, 0);
insert into pontuacoes (id_pontuacao, id_tipo_pontuacao, pontuacao, tempo_jogo) values (447, 2, 1, 0);
insert into pontuacoes (id_pontuacao, id_tipo_pontuacao, pontuacao, tempo_jogo) values (448, 2, 1, 0);
insert into pontuacoes (id_pontuacao, id_tipo_pontuacao, pontuacao, tempo_jogo) values (449, 2, 1, 0);
insert into pontuacoes (id_pontuacao, id_tipo_pontuacao, pontuacao, tempo_jogo) values (450, 2, 1, 0);
insert into pontuacoes (id_pontuacao, id_tipo_pontuacao, pontuacao, tempo_jogo) values (451, 2, 1, 0);
insert into pontuacoes (id_pontuacao, id_tipo_pontuacao, pontuacao, tempo_jogo) values (452, 2, 1, 0);
insert into pontuacoes (id_pontuacao, id_tipo_pontuacao, pontuacao, tempo_jogo) values (453, 2, 1, 0);
insert into pontuacoes (id_pontuacao, id_tipo_pontuacao, pontuacao, tempo_jogo) values (454, 2, 1, 0);
insert into pontuacoes (id_pontuacao, id_tipo_pontuacao, pontuacao, tempo_jogo) values (455, 2, 1, 0);
insert into pontuacoes (id_pontuacao, id_tipo_pontuacao, pontuacao, tempo_jogo) values (456, 2, 1, 0);
insert into pontuacoes (id_pontuacao, id_tipo_pontuacao, pontuacao, tempo_jogo) values (457, 2, 1, 0);
insert into pontuacoes (id_pontuacao, id_tipo_pontuacao, pontuacao, tempo_jogo) values (458, 2, 1, 0);
insert into pontuacoes (id_pontuacao, id_tipo_pontuacao, pontuacao, tempo_jogo) values (459, 2, 1, 0);
insert into pontuacoes (id_pontuacao, id_tipo_pontuacao, pontuacao, tempo_jogo) values (460, 2, 1, 0);
insert into pontuacoes (id_pontuacao, id_tipo_pontuacao, pontuacao, tempo_jogo) values (461, 2, 1, 0);
insert into pontuacoes (id_pontuacao, id_tipo_pontuacao, pontuacao, tempo_jogo) values (462, 2, 1, 0);
insert into pontuacoes (id_pontuacao, id_tipo_pontuacao, pontuacao, tempo_jogo) values (463, 2, 1, 0);
insert into pontuacoes (id_pontuacao, id_tipo_pontuacao, pontuacao, tempo_jogo) values (464, 2, 1, 0);
insert into pontuacoes (id_pontuacao, id_tipo_pontuacao, pontuacao, tempo_jogo) values (465, 2, 1, 0);
insert into pontuacoes (id_pontuacao, id_tipo_pontuacao, pontuacao, tempo_jogo) values (466, 2, 1, 0);
insert into pontuacoes (id_pontuacao, id_tipo_pontuacao, pontuacao, tempo_jogo) values (467, 2, 1, 0);
insert into pontuacoes (id_pontuacao, id_tipo_pontuacao, pontuacao, tempo_jogo) values (468, 2, 1, 0);
insert into pontuacoes (id_pontuacao, id_tipo_pontuacao, pontuacao, tempo_jogo) values (469, 2, 1, 0);
insert into pontuacoes (id_pontuacao, id_tipo_pontuacao, pontuacao, tempo_jogo) values (470, 2, 1, 0);
insert into pontuacoes (id_pontuacao, id_tipo_pontuacao, pontuacao, tempo_jogo) values (471, 2, 1, 0);
insert into pontuacoes (id_pontuacao, id_tipo_pontuacao, pontuacao, tempo_jogo) values (472, 2, 1, 0);
insert into pontuacoes (id_pontuacao, id_tipo_pontuacao, pontuacao, tempo_jogo) values (473, 2, 1, 0);
insert into pontuacoes (id_pontuacao, id_tipo_pontuacao, pontuacao, tempo_jogo) values (474, 2, 1, 0);
insert into pontuacoes (id_pontuacao, id_tipo_pontuacao, pontuacao, tempo_jogo) values (475, 2, 1, 0);
insert into pontuacoes (id_pontuacao, id_tipo_pontuacao, pontuacao, tempo_jogo) values (476, 2, 1, 0);
insert into pontuacoes (id_pontuacao, id_tipo_pontuacao, pontuacao, tempo_jogo) values (477, 2, 1, 0);
insert into pontuacoes (id_pontuacao, id_tipo_pontuacao, pontuacao, tempo_jogo) values (478, 2, 1, 0);
insert into pontuacoes (id_pontuacao, id_tipo_pontuacao, pontuacao, tempo_jogo) values (479, 2, 1, 0);
insert into pontuacoes (id_pontuacao, id_tipo_pontuacao, pontuacao, tempo_jogo) values (480, 2, 1, 0);
insert into pontuacoes (id_pontuacao, id_tipo_pontuacao, pontuacao, tempo_jogo) values (481, 2, 1, 0);
insert into pontuacoes (id_pontuacao, id_tipo_pontuacao, pontuacao, tempo_jogo) values (482, 2, 1, 0);
insert into pontuacoes (id_pontuacao, id_tipo_pontuacao, pontuacao, tempo_jogo) values (483, 2, 1, 0);
insert into pontuacoes (id_pontuacao, id_tipo_pontuacao, pontuacao, tempo_jogo) values (484, 2, 1, 0);
insert into pontuacoes (id_pontuacao, id_tipo_pontuacao, pontuacao, tempo_jogo) values (485, 2, 1, 0);
insert into pontuacoes (id_pontuacao, id_tipo_pontuacao, pontuacao, tempo_jogo) values (486, 2, 1, 0);
insert into pontuacoes (id_pontuacao, id_tipo_pontuacao, pontuacao, tempo_jogo) values (487, 2, 1, 0);
insert into pontuacoes (id_pontuacao, id_tipo_pontuacao, pontuacao, tempo_jogo) values (488, 2, 1, 0);
insert into pontuacoes (id_pontuacao, id_tipo_pontuacao, pontuacao, tempo_jogo) values (489, 2, 1, 0);
insert into pontuacoes (id_pontuacao, id_tipo_pontuacao, pontuacao, tempo_jogo) values (490, 2, 1, 0);
insert into pontuacoes (id_pontuacao, id_tipo_pontuacao, pontuacao, tempo_jogo) values (491, 2, 1, 0);
insert into pontuacoes (id_pontuacao, id_tipo_pontuacao, pontuacao, tempo_jogo) values (492, 2, 1, 0);
insert into pontuacoes (id_pontuacao, id_tipo_pontuacao, pontuacao, tempo_jogo) values (493, 2, 1, 0);
insert into pontuacoes (id_pontuacao, id_tipo_pontuacao, pontuacao, tempo_jogo) values (494, 2, 1, 0);
insert into pontuacoes (id_pontuacao, id_tipo_pontuacao, pontuacao, tempo_jogo) values (495, 2, 1, 0);
insert into pontuacoes (id_pontuacao, id_tipo_pontuacao, pontuacao, tempo_jogo) values (496, 2, 1, 0);
insert into pontuacoes (id_pontuacao, id_tipo_pontuacao, pontuacao, tempo_jogo) values (497, 2, 1, 0);
insert into pontuacoes (id_pontuacao, id_tipo_pontuacao, pontuacao, tempo_jogo) values (498, 2, 1, 0);
insert into pontuacoes (id_pontuacao, id_tipo_pontuacao, pontuacao, tempo_jogo) values (499, 2, 1, 0);
insert into pontuacoes (id_pontuacao, id_tipo_pontuacao, pontuacao, tempo_jogo) values (500, 2, 1, 0);
insert into pontuacoes (id_pontuacao, id_tipo_pontuacao, pontuacao, tempo_jogo) values (501, 1, 1, 32);
insert into pontuacoes (id_pontuacao, id_tipo_pontuacao, pontuacao, tempo_jogo) values (502, 1, 1, 34);
insert into pontuacoes (id_pontuacao, id_tipo_pontuacao, pontuacao, tempo_jogo) values (503, 1, 1, 1);
insert into pontuacoes (id_pontuacao, id_tipo_pontuacao, pontuacao, tempo_jogo) values (504, 1, 1, 39);
insert into pontuacoes (id_pontuacao, id_tipo_pontuacao, pontuacao, tempo_jogo) values (505, 1, 1, 17);
insert into pontuacoes (id_pontuacao, id_tipo_pontuacao, pontuacao, tempo_jogo) values (506, 1, 1, 20);
insert into pontuacoes (id_pontuacao, id_tipo_pontuacao, pontuacao, tempo_jogo) values (507, 1, 1, 21);
insert into pontuacoes (id_pontuacao, id_tipo_pontuacao, pontuacao, tempo_jogo) values (508, 1, 1, 30);
insert into pontuacoes (id_pontuacao, id_tipo_pontuacao, pontuacao, tempo_jogo) values (509, 1, 1, 4);
insert into pontuacoes (id_pontuacao, id_tipo_pontuacao, pontuacao, tempo_jogo) values (510, 1, 1, 4);
insert into pontuacoes (id_pontuacao, id_tipo_pontuacao, pontuacao, tempo_jogo) values (511, 1, 1, 23);
insert into pontuacoes (id_pontuacao, id_tipo_pontuacao, pontuacao, tempo_jogo) values (512, 1, 1, 7);
insert into pontuacoes (id_pontuacao, id_tipo_pontuacao, pontuacao, tempo_jogo) values (513, 1, 1, 36);
insert into pontuacoes (id_pontuacao, id_tipo_pontuacao, pontuacao, tempo_jogo) values (514, 1, 1, 16);
insert into pontuacoes (id_pontuacao, id_tipo_pontuacao, pontuacao, tempo_jogo) values (515, 1, 1, 15);
insert into pontuacoes (id_pontuacao, id_tipo_pontuacao, pontuacao, tempo_jogo) values (516, 1, 1, 18);
insert into pontuacoes (id_pontuacao, id_tipo_pontuacao, pontuacao, tempo_jogo) values (517, 1, 1, 17);
insert into pontuacoes (id_pontuacao, id_tipo_pontuacao, pontuacao, tempo_jogo) values (518, 1, 1, 6);
insert into pontuacoes (id_pontuacao, id_tipo_pontuacao, pontuacao, tempo_jogo) values (519, 1, 1, 34);
insert into pontuacoes (id_pontuacao, id_tipo_pontuacao, pontuacao, tempo_jogo) values (520, 1, 1, 3);
insert into pontuacoes (id_pontuacao, id_tipo_pontuacao, pontuacao, tempo_jogo) values (521, 1, 1, 18);
insert into pontuacoes (id_pontuacao, id_tipo_pontuacao, pontuacao, tempo_jogo) values (522, 1, 1, 36);
insert into pontuacoes (id_pontuacao, id_tipo_pontuacao, pontuacao, tempo_jogo) values (523, 1, 1, 34);
insert into pontuacoes (id_pontuacao, id_tipo_pontuacao, pontuacao, tempo_jogo) values (524, 1, 1, 5);
insert into pontuacoes (id_pontuacao, id_tipo_pontuacao, pontuacao, tempo_jogo) values (525, 1, 1, 38);
insert into pontuacoes (id_pontuacao, id_tipo_pontuacao, pontuacao, tempo_jogo) values (526, 1, 1, 9);
insert into pontuacoes (id_pontuacao, id_tipo_pontuacao, pontuacao, tempo_jogo) values (527, 1, 1, 14);
insert into pontuacoes (id_pontuacao, id_tipo_pontuacao, pontuacao, tempo_jogo) values (528, 1, 1, 3);
insert into pontuacoes (id_pontuacao, id_tipo_pontuacao, pontuacao, tempo_jogo) values (529, 1, 1, 13);
insert into pontuacoes (id_pontuacao, id_tipo_pontuacao, pontuacao, tempo_jogo) values (530, 1, 1, 40);
insert into pontuacoes (id_pontuacao, id_tipo_pontuacao, pontuacao, tempo_jogo) values (531, 1, 1, 37);
insert into pontuacoes (id_pontuacao, id_tipo_pontuacao, pontuacao, tempo_jogo) values (532, 1, 1, 16);
insert into pontuacoes (id_pontuacao, id_tipo_pontuacao, pontuacao, tempo_jogo) values (533, 1, 1, 38);
insert into pontuacoes (id_pontuacao, id_tipo_pontuacao, pontuacao, tempo_jogo) values (534, 1, 1, 1);
insert into pontuacoes (id_pontuacao, id_tipo_pontuacao, pontuacao, tempo_jogo) values (535, 1, 1, 34);
insert into pontuacoes (id_pontuacao, id_tipo_pontuacao, pontuacao, tempo_jogo) values (536, 1, 1, 20);
insert into pontuacoes (id_pontuacao, id_tipo_pontuacao, pontuacao, tempo_jogo) values (537, 1, 1, 36);
insert into pontuacoes (id_pontuacao, id_tipo_pontuacao, pontuacao, tempo_jogo) values (538, 1, 1, 15);
insert into pontuacoes (id_pontuacao, id_tipo_pontuacao, pontuacao, tempo_jogo) values (539, 1, 1, 3);
insert into pontuacoes (id_pontuacao, id_tipo_pontuacao, pontuacao, tempo_jogo) values (540, 1, 1, 4);
insert into pontuacoes (id_pontuacao, id_tipo_pontuacao, pontuacao, tempo_jogo) values (541, 1, 1, 23);
insert into pontuacoes (id_pontuacao, id_tipo_pontuacao, pontuacao, tempo_jogo) values (542, 1, 1, 33);
insert into pontuacoes (id_pontuacao, id_tipo_pontuacao, pontuacao, tempo_jogo) values (543, 1, 1, 1);
insert into pontuacoes (id_pontuacao, id_tipo_pontuacao, pontuacao, tempo_jogo) values (544, 1, 1, 22);
insert into pontuacoes (id_pontuacao, id_tipo_pontuacao, pontuacao, tempo_jogo) values (545, 1, 1, 32);
insert into pontuacoes (id_pontuacao, id_tipo_pontuacao, pontuacao, tempo_jogo) values (546, 1, 1, 22);
insert into pontuacoes (id_pontuacao, id_tipo_pontuacao, pontuacao, tempo_jogo) values (547, 1, 1, 9);
insert into pontuacoes (id_pontuacao, id_tipo_pontuacao, pontuacao, tempo_jogo) values (548, 1, 1, 31);
insert into pontuacoes (id_pontuacao, id_tipo_pontuacao, pontuacao, tempo_jogo) values (549, 1, 1, 29);
insert into pontuacoes (id_pontuacao, id_tipo_pontuacao, pontuacao, tempo_jogo) values (550, 1, 1, 24);
insert into pontuacoes (id_pontuacao, id_tipo_pontuacao, pontuacao, tempo_jogo) values (551, 1, 1, 4);
insert into pontuacoes (id_pontuacao, id_tipo_pontuacao, pontuacao, tempo_jogo) values (552, 1, 1, 10);
insert into pontuacoes (id_pontuacao, id_tipo_pontuacao, pontuacao, tempo_jogo) values (553, 1, 1, 15);
insert into pontuacoes (id_pontuacao, id_tipo_pontuacao, pontuacao, tempo_jogo) values (554, 1, 1, 25);
insert into pontuacoes (id_pontuacao, id_tipo_pontuacao, pontuacao, tempo_jogo) values (555, 1, 1, 24);
insert into pontuacoes (id_pontuacao, id_tipo_pontuacao, pontuacao, tempo_jogo) values (556, 1, 1, 17);
insert into pontuacoes (id_pontuacao, id_tipo_pontuacao, pontuacao, tempo_jogo) values (557, 1, 1, 15);
insert into pontuacoes (id_pontuacao, id_tipo_pontuacao, pontuacao, tempo_jogo) values (558, 1, 1, 9);
insert into pontuacoes (id_pontuacao, id_tipo_pontuacao, pontuacao, tempo_jogo) values (559, 1, 1, 10);
insert into pontuacoes (id_pontuacao, id_tipo_pontuacao, pontuacao, tempo_jogo) values (560, 1, 1, 24);
insert into pontuacoes (id_pontuacao, id_tipo_pontuacao, pontuacao, tempo_jogo) values (561, 1, 1, 11);
insert into pontuacoes (id_pontuacao, id_tipo_pontuacao, pontuacao, tempo_jogo) values (562, 1, 1, 35);
insert into pontuacoes (id_pontuacao, id_tipo_pontuacao, pontuacao, tempo_jogo) values (563, 1, 1, 29);
insert into pontuacoes (id_pontuacao, id_tipo_pontuacao, pontuacao, tempo_jogo) values (564, 1, 1, 38);
insert into pontuacoes (id_pontuacao, id_tipo_pontuacao, pontuacao, tempo_jogo) values (565, 1, 1, 31);
insert into pontuacoes (id_pontuacao, id_tipo_pontuacao, pontuacao, tempo_jogo) values (566, 1, 1, 13);
insert into pontuacoes (id_pontuacao, id_tipo_pontuacao, pontuacao, tempo_jogo) values (567, 1, 1, 31);
insert into pontuacoes (id_pontuacao, id_tipo_pontuacao, pontuacao, tempo_jogo) values (568, 1, 1, 28);
insert into pontuacoes (id_pontuacao, id_tipo_pontuacao, pontuacao, tempo_jogo) values (569, 1, 1, 10);
insert into pontuacoes (id_pontuacao, id_tipo_pontuacao, pontuacao, tempo_jogo) values (570, 1, 1, 37);
insert into pontuacoes (id_pontuacao, id_tipo_pontuacao, pontuacao, tempo_jogo) values (571, 1, 1, 33);
insert into pontuacoes (id_pontuacao, id_tipo_pontuacao, pontuacao, tempo_jogo) values (572, 1, 1, 37);
insert into pontuacoes (id_pontuacao, id_tipo_pontuacao, pontuacao, tempo_jogo) values (573, 1, 1, 15);
insert into pontuacoes (id_pontuacao, id_tipo_pontuacao, pontuacao, tempo_jogo) values (574, 1, 1, 2);
insert into pontuacoes (id_pontuacao, id_tipo_pontuacao, pontuacao, tempo_jogo) values (575, 1, 1, 21);
insert into pontuacoes (id_pontuacao, id_tipo_pontuacao, pontuacao, tempo_jogo) values (576, 1, 1, 30);
insert into pontuacoes (id_pontuacao, id_tipo_pontuacao, pontuacao, tempo_jogo) values (577, 1, 1, 17);
insert into pontuacoes (id_pontuacao, id_tipo_pontuacao, pontuacao, tempo_jogo) values (578, 1, 1, 29);
insert into pontuacoes (id_pontuacao, id_tipo_pontuacao, pontuacao, tempo_jogo) values (579, 1, 1, 38);
insert into pontuacoes (id_pontuacao, id_tipo_pontuacao, pontuacao, tempo_jogo) values (580, 1, 1, 20);
insert into pontuacoes (id_pontuacao, id_tipo_pontuacao, pontuacao, tempo_jogo) values (581, 1, 1, 13);
insert into pontuacoes (id_pontuacao, id_tipo_pontuacao, pontuacao, tempo_jogo) values (582, 1, 1, 1);
insert into pontuacoes (id_pontuacao, id_tipo_pontuacao, pontuacao, tempo_jogo) values (583, 1, 1, 27);
insert into pontuacoes (id_pontuacao, id_tipo_pontuacao, pontuacao, tempo_jogo) values (584, 1, 1, 28);
insert into pontuacoes (id_pontuacao, id_tipo_pontuacao, pontuacao, tempo_jogo) values (585, 1, 1, 20);
insert into pontuacoes (id_pontuacao, id_tipo_pontuacao, pontuacao, tempo_jogo) values (586, 1, 1, 21);
insert into pontuacoes (id_pontuacao, id_tipo_pontuacao, pontuacao, tempo_jogo) values (587, 1, 1, 31);
insert into pontuacoes (id_pontuacao, id_tipo_pontuacao, pontuacao, tempo_jogo) values (588, 1, 1, 7);
insert into pontuacoes (id_pontuacao, id_tipo_pontuacao, pontuacao, tempo_jogo) values (589, 1, 1, 20);
insert into pontuacoes (id_pontuacao, id_tipo_pontuacao, pontuacao, tempo_jogo) values (590, 1, 1, 25);
insert into pontuacoes (id_pontuacao, id_tipo_pontuacao, pontuacao, tempo_jogo) values (591, 1, 1, 15);
insert into pontuacoes (id_pontuacao, id_tipo_pontuacao, pontuacao, tempo_jogo) values (592, 1, 1, 28);
insert into pontuacoes (id_pontuacao, id_tipo_pontuacao, pontuacao, tempo_jogo) values (593, 1, 1, 14);
insert into pontuacoes (id_pontuacao, id_tipo_pontuacao, pontuacao, tempo_jogo) values (594, 1, 1, 18);
insert into pontuacoes (id_pontuacao, id_tipo_pontuacao, pontuacao, tempo_jogo) values (595, 1, 1, 30);
insert into pontuacoes (id_pontuacao, id_tipo_pontuacao, pontuacao, tempo_jogo) values (596, 1, 1, 30);
insert into pontuacoes (id_pontuacao, id_tipo_pontuacao, pontuacao, tempo_jogo) values (597, 1, 1, 5);
insert into pontuacoes (id_pontuacao, id_tipo_pontuacao, pontuacao, tempo_jogo) values (598, 1, 1, 39);
insert into pontuacoes (id_pontuacao, id_tipo_pontuacao, pontuacao, tempo_jogo) values (599, 1, 1, 9);
insert into pontuacoes (id_pontuacao, id_tipo_pontuacao, pontuacao, tempo_jogo) values (600, 1, 1, 19);
insert into pontuacoes (id_pontuacao, id_tipo_pontuacao, pontuacao, tempo_jogo) values (601, 1, 1, 18);
insert into pontuacoes (id_pontuacao, id_tipo_pontuacao, pontuacao, tempo_jogo) values (602, 1, 1, 1);
insert into pontuacoes (id_pontuacao, id_tipo_pontuacao, pontuacao, tempo_jogo) values (603, 1, 1, 39);
insert into pontuacoes (id_pontuacao, id_tipo_pontuacao, pontuacao, tempo_jogo) values (604, 1, 1, 12);
insert into pontuacoes (id_pontuacao, id_tipo_pontuacao, pontuacao, tempo_jogo) values (605, 1, 1, 13);
insert into pontuacoes (id_pontuacao, id_tipo_pontuacao, pontuacao, tempo_jogo) values (606, 1, 1, 39);
insert into pontuacoes (id_pontuacao, id_tipo_pontuacao, pontuacao, tempo_jogo) values (607, 1, 1, 37);
insert into pontuacoes (id_pontuacao, id_tipo_pontuacao, pontuacao, tempo_jogo) values (608, 1, 1, 5);
insert into pontuacoes (id_pontuacao, id_tipo_pontuacao, pontuacao, tempo_jogo) values (609, 1, 1, 18);
insert into pontuacoes (id_pontuacao, id_tipo_pontuacao, pontuacao, tempo_jogo) values (610, 1, 1, 17);
insert into pontuacoes (id_pontuacao, id_tipo_pontuacao, pontuacao, tempo_jogo) values (611, 1, 1, 22);
insert into pontuacoes (id_pontuacao, id_tipo_pontuacao, pontuacao, tempo_jogo) values (612, 1, 1, 30);
insert into pontuacoes (id_pontuacao, id_tipo_pontuacao, pontuacao, tempo_jogo) values (613, 1, 1, 11);
insert into pontuacoes (id_pontuacao, id_tipo_pontuacao, pontuacao, tempo_jogo) values (614, 1, 1, 21);
insert into pontuacoes (id_pontuacao, id_tipo_pontuacao, pontuacao, tempo_jogo) values (615, 1, 1, 29);
insert into pontuacoes (id_pontuacao, id_tipo_pontuacao, pontuacao, tempo_jogo) values (616, 1, 1, 4);
insert into pontuacoes (id_pontuacao, id_tipo_pontuacao, pontuacao, tempo_jogo) values (617, 1, 1, 18);
insert into pontuacoes (id_pontuacao, id_tipo_pontuacao, pontuacao, tempo_jogo) values (618, 1, 1, 15);
insert into pontuacoes (id_pontuacao, id_tipo_pontuacao, pontuacao, tempo_jogo) values (619, 1, 1, 7);
insert into pontuacoes (id_pontuacao, id_tipo_pontuacao, pontuacao, tempo_jogo) values (620, 1, 1, 3);
insert into pontuacoes (id_pontuacao, id_tipo_pontuacao, pontuacao, tempo_jogo) values (621, 1, 1, 26);
insert into pontuacoes (id_pontuacao, id_tipo_pontuacao, pontuacao, tempo_jogo) values (622, 1, 1, 39);
insert into pontuacoes (id_pontuacao, id_tipo_pontuacao, pontuacao, tempo_jogo) values (623, 1, 1, 6);
insert into pontuacoes (id_pontuacao, id_tipo_pontuacao, pontuacao, tempo_jogo) values (624, 1, 1, 21);
insert into pontuacoes (id_pontuacao, id_tipo_pontuacao, pontuacao, tempo_jogo) values (625, 1, 1, 34);
insert into pontuacoes (id_pontuacao, id_tipo_pontuacao, pontuacao, tempo_jogo) values (626, 1, 1, 27);
insert into pontuacoes (id_pontuacao, id_tipo_pontuacao, pontuacao, tempo_jogo) values (627, 1, 1, 32);
insert into pontuacoes (id_pontuacao, id_tipo_pontuacao, pontuacao, tempo_jogo) values (628, 1, 1, 19);
insert into pontuacoes (id_pontuacao, id_tipo_pontuacao, pontuacao, tempo_jogo) values (629, 1, 1, 23);
insert into pontuacoes (id_pontuacao, id_tipo_pontuacao, pontuacao, tempo_jogo) values (630, 1, 1, 39);
insert into pontuacoes (id_pontuacao, id_tipo_pontuacao, pontuacao, tempo_jogo) values (631, 1, 1, 32);
insert into pontuacoes (id_pontuacao, id_tipo_pontuacao, pontuacao, tempo_jogo) values (632, 1, 1, 31);
insert into pontuacoes (id_pontuacao, id_tipo_pontuacao, pontuacao, tempo_jogo) values (633, 1, 1, 7);
insert into pontuacoes (id_pontuacao, id_tipo_pontuacao, pontuacao, tempo_jogo) values (634, 1, 1, 33);
insert into pontuacoes (id_pontuacao, id_tipo_pontuacao, pontuacao, tempo_jogo) values (635, 1, 1, 19);
insert into pontuacoes (id_pontuacao, id_tipo_pontuacao, pontuacao, tempo_jogo) values (636, 1, 1, 40);
insert into pontuacoes (id_pontuacao, id_tipo_pontuacao, pontuacao, tempo_jogo) values (637, 1, 1, 6);
insert into pontuacoes (id_pontuacao, id_tipo_pontuacao, pontuacao, tempo_jogo) values (638, 1, 1, 38);
insert into pontuacoes (id_pontuacao, id_tipo_pontuacao, pontuacao, tempo_jogo) values (639, 1, 1, 15);
insert into pontuacoes (id_pontuacao, id_tipo_pontuacao, pontuacao, tempo_jogo) values (640, 1, 1, 10);
insert into pontuacoes (id_pontuacao, id_tipo_pontuacao, pontuacao, tempo_jogo) values (641, 1, 1, 12);
insert into pontuacoes (id_pontuacao, id_tipo_pontuacao, pontuacao, tempo_jogo) values (642, 1, 1, 36);
insert into pontuacoes (id_pontuacao, id_tipo_pontuacao, pontuacao, tempo_jogo) values (643, 1, 1, 27);
insert into pontuacoes (id_pontuacao, id_tipo_pontuacao, pontuacao, tempo_jogo) values (644, 1, 1, 36);
insert into pontuacoes (id_pontuacao, id_tipo_pontuacao, pontuacao, tempo_jogo) values (645, 1, 1, 8);
insert into pontuacoes (id_pontuacao, id_tipo_pontuacao, pontuacao, tempo_jogo) values (646, 1, 1, 24);
insert into pontuacoes (id_pontuacao, id_tipo_pontuacao, pontuacao, tempo_jogo) values (647, 1, 1, 2);
insert into pontuacoes (id_pontuacao, id_tipo_pontuacao, pontuacao, tempo_jogo) values (648, 1, 1, 13);
insert into pontuacoes (id_pontuacao, id_tipo_pontuacao, pontuacao, tempo_jogo) values (649, 1, 1, 28);
insert into pontuacoes (id_pontuacao, id_tipo_pontuacao, pontuacao, tempo_jogo) values (650, 1, 1, 11);
insert into pontuacoes (id_pontuacao, id_tipo_pontuacao, pontuacao, tempo_jogo) values (651, 1, 1, 25);
insert into pontuacoes (id_pontuacao, id_tipo_pontuacao, pontuacao, tempo_jogo) values (652, 1, 1, 32);
insert into pontuacoes (id_pontuacao, id_tipo_pontuacao, pontuacao, tempo_jogo) values (653, 1, 1, 26);
insert into pontuacoes (id_pontuacao, id_tipo_pontuacao, pontuacao, tempo_jogo) values (654, 1, 1, 21);
insert into pontuacoes (id_pontuacao, id_tipo_pontuacao, pontuacao, tempo_jogo) values (655, 1, 1, 29);
insert into pontuacoes (id_pontuacao, id_tipo_pontuacao, pontuacao, tempo_jogo) values (656, 1, 1, 8);
insert into pontuacoes (id_pontuacao, id_tipo_pontuacao, pontuacao, tempo_jogo) values (657, 1, 1, 9);
insert into pontuacoes (id_pontuacao, id_tipo_pontuacao, pontuacao, tempo_jogo) values (658, 1, 1, 14);
insert into pontuacoes (id_pontuacao, id_tipo_pontuacao, pontuacao, tempo_jogo) values (659, 1, 1, 36);
insert into pontuacoes (id_pontuacao, id_tipo_pontuacao, pontuacao, tempo_jogo) values (660, 1, 1, 21);
insert into pontuacoes (id_pontuacao, id_tipo_pontuacao, pontuacao, tempo_jogo) values (661, 1, 1, 11);
insert into pontuacoes (id_pontuacao, id_tipo_pontuacao, pontuacao, tempo_jogo) values (662, 1, 1, 1);
insert into pontuacoes (id_pontuacao, id_tipo_pontuacao, pontuacao, tempo_jogo) values (663, 1, 1, 12);
insert into pontuacoes (id_pontuacao, id_tipo_pontuacao, pontuacao, tempo_jogo) values (664, 1, 1, 10);
insert into pontuacoes (id_pontuacao, id_tipo_pontuacao, pontuacao, tempo_jogo) values (665, 1, 1, 21);
insert into pontuacoes (id_pontuacao, id_tipo_pontuacao, pontuacao, tempo_jogo) values (666, 1, 1, 23);
insert into pontuacoes (id_pontuacao, id_tipo_pontuacao, pontuacao, tempo_jogo) values (667, 1, 1, 32);
insert into pontuacoes (id_pontuacao, id_tipo_pontuacao, pontuacao, tempo_jogo) values (668, 1, 1, 21);
insert into pontuacoes (id_pontuacao, id_tipo_pontuacao, pontuacao, tempo_jogo) values (669, 1, 1, 40);
insert into pontuacoes (id_pontuacao, id_tipo_pontuacao, pontuacao, tempo_jogo) values (670, 1, 1, 12);
insert into pontuacoes (id_pontuacao, id_tipo_pontuacao, pontuacao, tempo_jogo) values (671, 1, 1, 1);
insert into pontuacoes (id_pontuacao, id_tipo_pontuacao, pontuacao, tempo_jogo) values (672, 1, 1, 21);
insert into pontuacoes (id_pontuacao, id_tipo_pontuacao, pontuacao, tempo_jogo) values (673, 1, 1, 27);
insert into pontuacoes (id_pontuacao, id_tipo_pontuacao, pontuacao, tempo_jogo) values (674, 1, 1, 18);
insert into pontuacoes (id_pontuacao, id_tipo_pontuacao, pontuacao, tempo_jogo) values (675, 1, 1, 2);
insert into pontuacoes (id_pontuacao, id_tipo_pontuacao, pontuacao, tempo_jogo) values (676, 1, 1, 15);
insert into pontuacoes (id_pontuacao, id_tipo_pontuacao, pontuacao, tempo_jogo) values (677, 1, 1, 24);
insert into pontuacoes (id_pontuacao, id_tipo_pontuacao, pontuacao, tempo_jogo) values (678, 1, 1, 2);
insert into pontuacoes (id_pontuacao, id_tipo_pontuacao, pontuacao, tempo_jogo) values (679, 1, 1, 40);
insert into pontuacoes (id_pontuacao, id_tipo_pontuacao, pontuacao, tempo_jogo) values (680, 1, 1, 6);
insert into pontuacoes (id_pontuacao, id_tipo_pontuacao, pontuacao, tempo_jogo) values (681, 1, 1, 20);
insert into pontuacoes (id_pontuacao, id_tipo_pontuacao, pontuacao, tempo_jogo) values (682, 1, 1, 2);
insert into pontuacoes (id_pontuacao, id_tipo_pontuacao, pontuacao, tempo_jogo) values (683, 1, 1, 3);
insert into pontuacoes (id_pontuacao, id_tipo_pontuacao, pontuacao, tempo_jogo) values (684, 1, 1, 1);
insert into pontuacoes (id_pontuacao, id_tipo_pontuacao, pontuacao, tempo_jogo) values (685, 1, 1, 26);
insert into pontuacoes (id_pontuacao, id_tipo_pontuacao, pontuacao, tempo_jogo) values (686, 1, 1, 23);
insert into pontuacoes (id_pontuacao, id_tipo_pontuacao, pontuacao, tempo_jogo) values (687, 1, 1, 25);
insert into pontuacoes (id_pontuacao, id_tipo_pontuacao, pontuacao, tempo_jogo) values (688, 1, 1, 25);
insert into pontuacoes (id_pontuacao, id_tipo_pontuacao, pontuacao, tempo_jogo) values (689, 1, 1, 6);
insert into pontuacoes (id_pontuacao, id_tipo_pontuacao, pontuacao, tempo_jogo) values (690, 1, 1, 2);
insert into pontuacoes (id_pontuacao, id_tipo_pontuacao, pontuacao, tempo_jogo) values (691, 1, 1, 29);
insert into pontuacoes (id_pontuacao, id_tipo_pontuacao, pontuacao, tempo_jogo) values (692, 1, 1, 18);
insert into pontuacoes (id_pontuacao, id_tipo_pontuacao, pontuacao, tempo_jogo) values (693, 1, 1, 35);
insert into pontuacoes (id_pontuacao, id_tipo_pontuacao, pontuacao, tempo_jogo) values (694, 1, 1, 38);
insert into pontuacoes (id_pontuacao, id_tipo_pontuacao, pontuacao, tempo_jogo) values (695, 1, 1, 8);
insert into pontuacoes (id_pontuacao, id_tipo_pontuacao, pontuacao, tempo_jogo) values (696, 1, 1, 38);
insert into pontuacoes (id_pontuacao, id_tipo_pontuacao, pontuacao, tempo_jogo) values (697, 1, 1, 27);
insert into pontuacoes (id_pontuacao, id_tipo_pontuacao, pontuacao, tempo_jogo) values (698, 1, 1, 31);
insert into pontuacoes (id_pontuacao, id_tipo_pontuacao, pontuacao, tempo_jogo) values (699, 1, 1, 1);
insert into pontuacoes (id_pontuacao, id_tipo_pontuacao, pontuacao, tempo_jogo) values (700, 1, 1, 36);



	